// THROWAWAY dev preview: the unified "search -> resolve -> learn" view.
// Real embedding-based resolution (local resolve_server.py, same technique
// as the semantic bridge), real matched chapter + sim content, real cement-
// understanding question from the live question bank. NOT personalized:
// this chapter text is the same for every student right now, flagged
// honestly in the UI rather than pretended otherwise. Delete this file and
// its route in App.tsx when done.
//
// Layout: full-screen graph + bottom search before any search; after resolve,
// the matched node highlights on the still-full-screen graph, then ~1.6s later
// the view splits: chapter as a stack of cards on the left (summary card,
// chunked content cards, related-concepts navigator), simulation dominating
// the right. When a concept has no sim, the right side shows an honest empty
// state instead of collapsing. The check-question modal only fires after the
// panel reveal has fully settled, never racing the transition.
//
// The graph is the whole content library now, not just act-math: the iframe
// loads /full-graph-viewer.html over /full-concept-graph.json, regenerated by
// scripts/export_concept_graph.py after each content-merge round. Chapter text
// and sims come from the whole library too, fetched one concept at a time from
// resolve_server.py's GET /content?id=<conceptId>, so a hit in biology or
// chemistry renders its real lesson and its real sim, not just a highlight.
// The static act-math jarvisBundle stays as an instant fast path for the 42
// concepts it covers (its jarvis-matched chapters and sims carry match scores
// the raw library lessons do not), and everything else loads on demand. The
// full graph_data.json is ~14 MB with every lesson inlined, so it is
// deliberately never bundled into the build or fetched whole by the browser.
import { useState, useEffect, useRef, type CSSProperties } from 'react'
import ColdCheckPrompt from '../components/ColdCheckPrompt'
import { getQuestions, type Question } from '../lib/questionBank'
import bundle from '../data/jarvisBundle.json'

const RESOLVE_URL = 'http://localhost:8099'
const CONTENT_URL = 'http://localhost:8099/content'
const GENERATE_URL = 'http://localhost:8101'
const PERSONALIZE_URL = 'http://localhost:8101/personalize'
const SIMPLIFY_URL = 'http://localhost:8101/simplify'
const GENERATE_SIM_URL = 'http://localhost:8102'
// Per-concept study history. localStorage only: this is a dev prototype with
// no auth and no backend, so the record is honestly per-browser and nothing
// pretends otherwise.
// v2: what counts as studied got stricter (answered the check question, not
// just had a chapter on screen), so v1's looser history is deliberately not
// carried forward rather than showing a count that no longer matches its own
// definition.
const STUDY_KEY = 'mindcraft.dev.studied.v2'
const CONFIDENCE_THRESHOLD = 0.5
const NO_COVERAGE_FLOOR = 0.35 // below this, even the "best available" match is noise, not a real signal
const RAMP_CONFIDENCE_CEILING = 0.6 // below this, a query is probably broad/exploratory, so start at the ramp's foundation, not the advanced concept it happened to score highest against
const REVEAL_DELAY_MS = 1600 // full-screen highlight stage before the split
const SETTLE_DELAY_MS = 700 // panel transition length, nothing modal before this

// One shape for both content sources. The act-math bundle carries a match
// score per chapter and sim (it was assembled by matching, so the score is
// real); the library endpoint serves a concept's own lesson, where there is
// nothing to score, hence the optional score and subject title.
interface ContentEntry {
  conceptId?: string
  label: string
  subjectTitle?: string
  chapter: { score?: number; title: string; summary: string; body: string; source?: string } | null
  sim: { score?: number; title: string; html: string } | null
}
const jarvisBundle = bundle as unknown as Record<string, ContentEntry>

// Shape written by scripts/export_concept_graph.py from the live content
// graph. Ids come in two shapes and both are handled as opaque strings: bare
// act-math ids ("circles_geometry") and subject-prefixed ids everywhere else
// ("biology::phylogenetics").
interface GraphNode { id: string; name: string; subject: string; level: string; hasLesson: boolean; hasSim: boolean }
interface GraphEdge { source: string; target: string; relation: string; weight: number }
interface GraphSubject { id: string; title: string; color: string; nodeCount: number; withLesson: number; withSim: number }
interface GraphCounts { nodes: number; edges: number; withLesson: number; withSim: number; subjects: number }

interface Match { conceptId: string; label: string; score: number; subject?: string }

// One step of the guided prerequisite path the resolver now returns alongside
// the matches, ordered foundational-first and always ending with the concept
// that was actually resolved. Every step is guaranteed lesson-bearing, so any
// chip in the strip is safe to click.
interface PathStep { conceptId: string; label: string; hasLesson: boolean; hasSim: boolean; level?: string; subject?: string }

// "Answered this concept's check question", right or wrong, the one real
// engagement signal this page has. Not a mastery model, and deliberately not
// triggered by a chapter merely being on screen, glancing at a step while
// walking a guided path should not count as having studied it.
interface StudyRecord { firstCompletedAt: number; lastCompletedAt: number }
type StudyLog = Record<string, StudyRecord>

// Every access is wrapped: a private window, cleared site data, or a browser
// set to block storage all throw here, and none of that should break the page.
function readStudyLog(): StudyLog {
  try {
    const raw = localStorage.getItem(STUDY_KEY)
    if (!raw) return {}
    const parsed = JSON.parse(raw)
    return parsed && typeof parsed === 'object' ? (parsed as StudyLog) : {}
  } catch {
    return {}
  }
}

function writeStudyLog(log: StudyLog) {
  try {
    localStorage.setItem(STUDY_KEY, JSON.stringify(log))
  } catch {
    // Storage unavailable. The in-memory copy still drives this session's UI.
  }
}

// ---- shared card look (dark translation of the soft-depth dashboard ref) ----
const CARD: CSSProperties = {
  background: '#13131C',
  border: '1px solid rgba(255,255,255,0.07)',
  borderRadius: 16,
  boxShadow: '0 12px 32px rgba(0,0,0,0.38)',
}

function Eyebrow({ color, children }: { color: string; children: React.ReactNode }) {
  return (
    <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: 1.2, textTransform: 'uppercase', color }}>
      {children}
    </div>
  )
}

export default function DevUnifiedLearn() {
  const [query, setQuery] = useState('')
  const [loading, setLoading] = useState(false)
  const [matches, setMatches] = useState<Match[] | null>(null)
  const [resolved, setResolved] = useState<Match | null>(null)
  const [outOfDomain, setOutOfDomain] = useState(false)
  const [panelsRevealed, setPanelsRevealed] = useState(false)
  const [panelsSettled, setPanelsSettled] = useState(false)
  const [checkQuestion, setCheckQuestion] = useState<Question | null>(null)
  const [checkResult, setCheckResult] = useState<string>('')
  const [err, setErr] = useState('')
  const [content, setContent] = useState<ContentEntry | null>(null)
  const [contentLoading, setContentLoading] = useState(false)
  const [contentFailed, setContentFailed] = useState('')
  const [generating, setGenerating] = useState(false)
  const [generateFailed, setGenerateFailed] = useState('')
  const [persona, setPersona] = useState('a 12-year-old girl who loves animals and figure skating, not cars or engineering')
  const [personalizing, setPersonalizing] = useState(false)
  const [personalizedBody, setPersonalizedBody] = useState('')
  const [personalizeFailed, setPersonalizeFailed] = useState('')
  const [showPersonalized, setShowPersonalized] = useState(false)
  // Guided prerequisite path. Empty or length 1 means there was no real ramp to
  // walk and the page behaves exactly as it did before.
  const [path, setPath] = useState<PathStep[]>([])
  const [pathIndex, setPathIndex] = useState(0)
  const [generatedSim, setGeneratedSim] = useState<{ title: string; html: string; reviewSummary?: string } | null>(null)
  const [simGenerating, setSimGenerating] = useState(false)
  const [simGenFailed, setSimGenFailed] = useState('')
  // Auto-simplified default reading of the chapter, from the student's own
  // query. Separate from the manual persona rewrite, which stays as an override.
  const [simplifiedBody, setSimplifiedBody] = useState('')
  const [simplifying, setSimplifying] = useState(false)
  const [simplifyFailed, setSimplifyFailed] = useState('')
  const [showSimplified, setShowSimplified] = useState(true)
  const [simplifyMeta, setSimplifyMeta] = useState<{ reductionPct: number } | null>(null)
  // The query as it was at search time, not the live input, so editing the box
  // afterwards cannot change what the simplifier was told about the student.
  const [searchedQuery, setSearchedQuery] = useState('')
  const [studyLog, setStudyLog] = useState<StudyLog>(() => readStudyLog())
  const graphIframeRef = useRef<HTMLIFrameElement>(null)
  const simplifyStartedForRef = useRef<string | null>(null)
  const simGenStartedForRef = useRef<string | null>(null)
  // Which concept a check question has already been started for, so the
  // question fires exactly once per resolution even though its effect now
  // also has to wait on an async content fetch.
  const checkStartedForRef = useRef<string | null>(null)
  const [graphNodes, setGraphNodes] = useState<GraphNode[]>([])
  const [graphEdges, setGraphEdges] = useState<GraphEdge[]>([])
  const [graphSubjects, setGraphSubjects] = useState<GraphSubject[]>([])
  const [graphCounts, setGraphCounts] = useState<GraphCounts | null>(null)

  useEffect(() => {
    fetch('/full-concept-graph.json')
      .then(r => r.json())
      .then(d => {
        setGraphNodes(d.nodes || [])
        setGraphEdges(d.edges || [])
        setGraphSubjects(d.subjects || [])
        setGraphCounts(d.counts || null)
      })
      .catch(() => {})
  }, [])

  function highlightInGraph(conceptId: string) {
    const neighborIds = graphEdges
      .filter(e => e.source === conceptId || e.target === conceptId)
      .map(e => (e.source === conceptId ? e.target : e.source))
    graphIframeRef.current?.contentWindow?.postMessage({ type: 'highlight', nodeId: conceptId, neighborIds }, '*')
  }

  // Real chapter body and sim HTML for one concept, pulled on demand from the
  // local content server. Ids are opaque here, exactly as in the graph
  // highlight path: bare act-math ids ("circles_geometry") and prefixed ones
  // ("biology::phylogenetics") both go through unchanged.
  // keepPreviousWhileLoading is for stepping along the guided path: clearing
  // content first would drop entry?.chapter, which collapses showPanels and
  // bounces the student back to the full-screen graph for the length of one
  // fetch. Holding the old chapter until the new one lands avoids that flash.
  // It is never used to hide a failure: every failure path clears it.
  async function loadContent(conceptId: string, keepPreviousWhileLoading = false) {
    setContentFailed('')
    if (jarvisBundle[conceptId]?.chapter) { setContent(null); return } // fast path, nothing to fetch
    if (!keepPreviousWhileLoading) setContent(null)
    setContentLoading(true)
    try {
      const res = await fetch(`${CONTENT_URL}?id=${encodeURIComponent(conceptId)}`)
      const data = await res.json()
      if (!res.ok || data.error) {
        setContent(null)
        setContentFailed(`Content server has no entry for ${conceptId} (${data.error ?? res.status}).`)
        return
      }
      setContent(data as ContentEntry)
    } catch {
      setContent(null)
      setContentFailed('Content not reachable at localhost:8099/content, is resolve_server.py running?')
    } finally {
      setContentLoading(false)
    }
  }

  async function tryPersonalize(chapterBody: string) {
    setPersonalizing(true)
    setPersonalizeFailed('')
    setPersonalizedBody('')
    try {
      const res = await fetch(PERSONALIZE_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ chapterBody, persona }),
      })
      const data = await res.json()
      if (!data.verified) {
        setPersonalizeFailed(`Rewrite failed the math fact-check (${data.reason}), not shown. This is the check working as designed.`)
        return
      }
      setPersonalizedBody(data.personalizedBody)
      setShowPersonalized(true)
    } catch {
      setPersonalizeFailed('Generator not reachable at localhost:8101.')
    } finally {
      setPersonalizing(false)
    }
  }

  async function tryGenerate(conceptLabel: string, chapterBody: string, conceptId: string) {
    setGenerating(true)
    setGenerateFailed('')
    try {
      const res = await fetch(GENERATE_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ conceptLabel, chapterBody }),
      })
      const data = await res.json()
      if (!data.verified) {
        setGenerateFailed(`Generated question failed independent verification (${data.reason}), not shown. This is the check working as designed, not a bug.`)
        return
      }
      setCheckQuestion({
        id: `generated-${Date.now()}`,
        conceptId,
        level: 1,
        question: data.question,
        choices: data.choices,
        correctIndex: data.correctIndex,
        explanation: data.explanation,
        hints: [],
      })
    } catch {
      setGenerateFailed('Generator not reachable at localhost:8101, is generate_check_server.py running?')
    } finally {
      setGenerating(false)
    }
  }

  // A sim generated live for a concept the library has none for. Same honesty
  // contract as tryGenerate: the server only returns HTML that passed an
  // independent review, so a failure here is shown, never papered over.
  async function trySimGenerate(conceptId: string, conceptLabel: string, chapterBody: string) {
    setSimGenerating(true)
    setSimGenFailed('')
    setGeneratedSim(null)
    try {
      const res = await fetch(GENERATE_SIM_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ conceptId, conceptLabel, chapterBody }),
      })
      const data = await res.json()
      if (!data.verified) {
        setSimGenFailed(`Generated sim did not pass independent review (${data.reason}). Not shown. The check working as designed, not a bug.`)
        return
      }
      setGeneratedSim({ title: data.title, html: data.html, reviewSummary: data.reviewSummary })
    } catch {
      setSimGenFailed('Sim generator not reachable at localhost:8102, is generate_sim_server.py running?')
    } finally {
      setSimGenerating(false)
    }
  }

  // The automatic, no-typing-required rewrite: shorter and plainer, pitched
  // from how the student phrased their own search. Same two-call discipline as
  // tryPersonalize, so a rewrite that cannot be shown to preserve the content
  // is not shown at all and the original stands.
  async function trySimplify(chapterBody: string, forQuery: string) {
    setSimplifying(true)
    setSimplifyFailed('')
    setSimplifiedBody('')
    setSimplifyMeta(null)
    try {
      const res = await fetch(SIMPLIFY_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ chapterBody, query: forQuery }),
      })
      const data = await res.json()
      if (!data.verified) {
        setSimplifyFailed(data.reason || 'not verified')
        return
      }
      setSimplifiedBody(data.simplifiedBody)
      setSimplifyMeta({ reductionPct: data.reductionPct })
      setShowSimplified(true)
    } catch {
      setSimplifyFailed('simplifier not reachable at localhost:8101')
    } finally {
      setSimplifying(false)
    }
  }

  // Record that this concept's check question was actually answered. Merges
  // into whatever is already stored so a reload keeps the history.
  function recordStudied(conceptId: string) {
    if (!conceptId) return
    setStudyLog(prev => {
      const now = Date.now()
      const existing = prev[conceptId]
      const next: StudyLog = {
        ...prev,
        [conceptId]: { firstCompletedAt: existing?.firstCompletedAt ?? now, lastCompletedAt: now },
      }
      writeStudyLog(next)
      return next
    })
  }

  function pushStudiedToGraph(log: StudyLog) {
    graphIframeRef.current?.contentWindow?.postMessage({ type: 'studied', ids: Object.keys(log) }, '*')
  }

  // Everything that is about one concept rather than one search, cleared
  // whenever the viewed concept changes: a new search, or a step in the path.
  function resetPerConcept(keepContent = false) {
    setCheckQuestion(null)
    setCheckResult('')
    setGenerateFailed('')
    setPersonalizedBody('')
    setPersonalizeFailed('')
    setShowPersonalized(false)
    if (!keepContent) setContent(null)
    setContentFailed('')
    setGeneratedSim(null)
    setSimGenFailed('')
    setSimGenerating(false)
    setSimplifiedBody('')
    setSimplifyFailed('')
    setSimplifying(false)
    setSimplifyMeta(null)
    setShowSimplified(true)
    checkStartedForRef.current = null
    simplifyStartedForRef.current = null
    simGenStartedForRef.current = null
  }

  // Move to one step of the guided path. Deliberately reuses loadContent and
  // highlightInGraph rather than adding a second data path, so a step behaves
  // exactly like a resolved concept already does.
  function goToStep(i: number) {
    const step = path[i]
    if (!step) return
    setPathIndex(i)
    resetPerConcept(true)
    void loadContent(step.conceptId, true)
    highlightInGraph(step.conceptId)
  }

  async function search(text?: string) {
    const q = (text ?? query).trim()
    if (!q) return
    setLoading(true)
    setErr('')
    setSearchedQuery(q)
    setResolved(null)
    setOutOfDomain(false)
    setPanelsRevealed(false)
    setPanelsSettled(false)
    setPath([])
    setPathIndex(0)
    resetPerConcept()
    try {
      const res = await fetch(RESOLVE_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: q }),
      })
      const data = await res.json()
      const ms: Match[] = data.matches
      setMatches(ms)
      if (ms[0].score < NO_COVERAGE_FLOOR) {
        // The raw top match itself is noise-level, meaning nothing in the whole
        // indexed library is actually about this query. Don't dress up a
        // near-zero score as content just because something has a chapter.
        setOutOfDomain(true)
        setResolved(ms[0])
        return
      }
      setOutOfDomain(false)
      // Honest fallback: prefer the highest-scoring match that actually has
      // renderable chapter text, rather than forcing the raw #1 if it's a
      // coverage gap. The resolver only indexes lesson-bearing concepts and
      // the content endpoint now serves every subject, so in practice the raw
      // #1 wins; this stays as a near-tie guard for the case where the graph
      // says a top match has no lesson.
      const NEAR_TIE = 0.08
      const hasChapter = (id: string) =>
        !!jarvisBundle[id]?.chapter || nodeById.get(id)?.hasLesson === true
      const withContent = ms.find(m => hasChapter(m.conceptId) && ms[0].score - m.score <= NEAR_TIE)
      const best = withContent ?? ms[0]
      setResolved(best)
      // The resolver builds the prerequisite ramp for its own top match. If the
      // near-tie guard above picked a different concept, that ramp is not about
      // the concept being shown, so it is dropped rather than mislabelled.
      const returned: PathStep[] = Array.isArray(data.path) ? data.path : []
      const ramp = returned.length > 1 && returned[returned.length - 1].conceptId === best.conceptId ? returned : []
      setPath(ramp)
      // A vague query ("what is calculus") should start at the FOUNDATION of the
      // ramp, not at the advanced concept raw similarity happened to land on.
      // A precise, confident query ("circles and their properties") already
      // named what the student wants: start there, with the ramp still shown
      // as context to look back through, not as a detour forced in front of it.
      const startAtFoundation = ramp.length > 1 && best.score < RAMP_CONFIDENCE_CEILING
      const startIndex = startAtFoundation ? 0 : ramp.length - 1
      setPathIndex(startIndex)
      const startId = startAtFoundation ? ramp[0].conceptId : best.conceptId
      void loadContent(startId)
      highlightInGraph(startId)
      // Let the highlight + camera move land on the full-screen graph first,
      // then split into the panels - not both at once. The check question is
      // NOT kicked off here, it waits for the panels to settle (see effect
      // below), so the modal can never race ahead of the reveal.
      setTimeout(() => setPanelsRevealed(true), REVEAL_DELAY_MS)
    } catch {
      setErr('Resolver not reachable at localhost:8099, is resolve_server.py running?')
    } finally {
      setLoading(false)
    }
  }

  // ---------------------------------------------------------------------
  // Derived state. Everything below is read by the hooks further down, so it
  // MUST stay declared above them: a const referenced by a hook that runs
  // earlier in file order is a temporal-dead-zone ReferenceError that blanks
  // the whole page on first render. Add new derived values here, not below.
  // ---------------------------------------------------------------------

  // Which concept the panels are actually showing. With a guided path that is
  // the current step, which starts at the foundational end; without one it is
  // just the resolved concept, so the rest of the page needs no special case.
  const hasPath = path.length > 1
  const activeStep = hasPath ? (path[pathIndex] ?? path[path.length - 1]) : null
  const activeConceptId = activeStep?.conceptId ?? resolved?.conceptId ?? null
  const isLastStep = !hasPath || pathIndex >= path.length - 1
  const nextStep = hasPath && !isLastStep ? path[pathIndex + 1] : null

  // One entry for both content sources: the act-math fast path (jarvisBundle,
  // no fetch needed) or the fetched `content` state for every other subject.
  // loadContent() only ever sets `content` when it actually fetched, so the
  // fallback below never shadows a real fast-path bundle hit.
  const bundleEntry = activeConceptId ? jarvisBundle[activeConceptId] ?? null : null
  const entry = content ?? bundleEntry
  const belowThreshold = resolved && resolved.score < CONFIDENCE_THRESHOLD
  const showPanels = !!(resolved && !outOfDomain && entry?.chapter && panelsRevealed)
  const chapter = showPanels && entry ? entry.chapter : null
  // The two sources are complementary, not ranked, for some act-math concepts.
  // circles_geometry is the clear case: the library server holds its chapter
  // and the jarvis bundle holds its sim, so taking the server entry wholesale
  // silently dropped a sim that exists. Chapter still prefers the server; the
  // bundle only fills a sim the server does not have.
  const sim = showPanels ? (entry?.sim ?? bundleEntry?.sim ?? null) : null

  // Which reading of the chapter is on screen. The manual persona rewrite is an
  // explicit override and wins; the auto-simplified version is the default when
  // it verified; the original is the floor and what a failure falls back to.
  const usingPersonalized = showPersonalized && !!personalizedBody
  const usingSimplified = !usingPersonalized && showSimplified && !!simplifiedBody
  const bodyVariant = usingPersonalized ? 'p' : usingSimplified ? 's' : 'o'
  const studiedIds = Object.keys(studyLog)
  const isStudied = (id: string) => !!studyLog[id]

  // Chapter body -> cards: paragraphs grouped in pairs so each card is one
  // digestible chunk instead of a single wall of prose.
  const activeBody = usingPersonalized ? personalizedBody : usingSimplified ? simplifiedBody : chapter?.body ?? ''
  const paras = activeBody.split('\n\n').map(p => p.trim()).filter(Boolean)
  const chunks: string[][] = []
  for (let i = 0; i < paras.length; i += 2) chunks.push(paras.slice(i, i + 2))

  // Auto-simplify fires as soon as the chapter for the active concept is real
  // and settled, once per concept. It does NOT wait for the panel reveal the
  // way the check question does: the check question is an interruption and has
  // to be timed, this is just the default text and should be ready as early as
  // possible.
  useEffect(() => {
    if (!resolved || outOfDomain || !activeConceptId) return
    if (contentLoading || !entry?.chapter) return
    if (simplifyStartedForRef.current === activeConceptId) return
    simplifyStartedForRef.current = activeConceptId
    void trySimplify(entry.chapter.body, searchedQuery)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [entry, activeConceptId, contentLoading, resolved, outOfDomain])

  // Preload a sim for a concept the library has none for, same instinct as
  // auto-simplify: do not make the student ask for it. Only ever fires once
  // per concept (the ref guard), and never fires when a real, pre-written sim
  // already covers this concept, there is nothing to fill in that case.
  useEffect(() => {
    if (!showPanels || !activeConceptId || !entry?.chapter) return
    if (sim) return
    if (simGenStartedForRef.current === activeConceptId) return
    simGenStartedForRef.current = activeConceptId
    void trySimGenerate(activeConceptId, entry.label, entry.chapter.body)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [showPanels, activeConceptId, entry, sim])

  // Keep the 3D graph's studied markers in sync, including on its first load,
  // which can land after the history has already been read from localStorage.
  useEffect(() => {
    pushStudiedToGraph(studyLog)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [studyLog])

  // Panels count as "settled" only after the reveal transition has played out.
  useEffect(() => {
    if (!panelsRevealed) { setPanelsSettled(false); return }
    const t = setTimeout(() => setPanelsSettled(true), SETTLE_DELAY_MS)
    return () => clearTimeout(t)
  }, [panelsRevealed])

  // Cement-understanding question: bank lookup / live generation starts only
  // once the panels have settled, this is the modal-timing bug fix. It now
  // also waits for the fetched chapter, since the text it generates from can
  // arrive after the settle for a non-act-math concept; the ref keeps that to
  // one attempt per resolution.
  // It keys off the ACTIVE concept, not the resolved one, so walking the
  // guided path gets a check question per step rather than one for a concept
  // the student has not reached yet.
  useEffect(() => {
    if (!panelsSettled || !resolved || outOfDomain || !activeConceptId) return
    // While a step is still fetching, `entry` is deliberately the PREVIOUS
    // step's chapter (see loadContent). Generating a question from it would
    // key the wrong text to the new concept, so wait for the swap.
    if (contentLoading) return
    if (!entry?.chapter) return
    if (checkStartedForRef.current === activeConceptId) return
    checkStartedForRef.current = activeConceptId
    const q = getQuestions(activeConceptId, 1, 1, [])
    if (q[0]) {
      setCheckQuestion(q[0])
    } else {
      // Bank has nothing for this concept, generate one live, with
      // independent verification, instead of just giving up.
      void tryGenerate(entry.label, entry.chapter.body, activeConceptId)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [panelsSettled, entry, activeConceptId, contentLoading])

  function backToGraph() {
    setResolved(null)
    setMatches(null)
    setOutOfDomain(false)
    setPanelsRevealed(false)
    setPanelsSettled(false)
    setPath([])
    setPathIndex(0)
    resetPerConcept()
    graphIframeRef.current?.contentWindow?.postMessage({ type: 'clear' }, '*')
  }

  // Real graph neighbors of the concept currently being shown (same edges the
  // 3D highlight uses), for the related-concepts navigator. Keyed to the active
  // step so the suggestions follow the student along the path.
  const nodeById = new Map(graphNodes.map(n => [n.id, n]))
  const subjectById = new Map(graphSubjects.map(s => [s.id, s]))
  const resolvedNode = resolved ? nodeById.get(resolved.conceptId) ?? null : null
  const activeLabel = activeStep?.label ?? entry?.label ?? resolved?.label ?? ''
  const neighborWeights = new Map<string, number>()
  if (activeConceptId) {
    for (const e of graphEdges) {
      const other = e.source === activeConceptId ? e.target : e.target === activeConceptId ? e.source : null
      if (other) neighborWeights.set(other, Math.max(neighborWeights.get(other) ?? 0, e.weight))
    }
  }
  const neighbors = [...neighborWeights.entries()]
    .map(([id, weight]) => {
      const node = nodeById.get(id)
      return {
        id,
        weight,
        label: node?.name ?? jarvisBundle[id]?.label ?? id,
        group: node ? `${subjectById.get(node.subject)?.title ?? node.subject} · ${node.level.replace(/_/g, ' ')}` : '',
        hasChapter: node ? node.hasLesson : !!jarvisBundle[id]?.chapter,
        hasSim: node ? node.hasSim : !!jarvisBundle[id]?.sim,
      }
    })
    .sort((a, b) => b.weight - a.weight)
  const maxNeighborWeight = neighbors[0]?.weight ?? 1

  return (
    <div style={{ height: '100vh', width: '100vw', background: '#0A0A0F', color: 'white', fontFamily: 'system-ui', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
      <style>{`
        @keyframes dulRise { from { opacity: 0; transform: translateY(16px); } to { opacity: 1; transform: none; } }
        .dul-col { scrollbar-width: thin; scrollbar-color: rgba(255,255,255,0.18) transparent; }
        .dul-col::-webkit-scrollbar { width: 8px; }
        .dul-col::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.14); border-radius: 4px; }
        .dul-neighbor { transition: background .15s ease, border-color .15s ease, transform .15s ease; }
        .dul-neighbor:hover { background: rgba(99,102,241,0.13) !important; border-color: rgba(99,102,241,0.5) !important; transform: translateX(3px); }
        .dul-input:focus { outline: none; border-color: rgba(99,102,241,0.65) !important; box-shadow: 0 0 0 3px rgba(99,102,241,0.18); }
      `}</style>

      {resolved && (
        <div style={{ padding: '10px 20px', fontSize: 12, display: 'flex', alignItems: 'center', gap: 12, flexShrink: 0, borderBottom: '1px solid rgba(255,255,255,0.06)', background: 'rgba(255,255,255,0.02)', color: outOfDomain ? '#FF6B6B' : belowThreshold ? '#F0C060' : 'rgba(255,255,255,0.5)' }}>
          <span style={{ flex: 1, minWidth: 0 }}>
            {outOfDomain ? (
              <>Closest match was <b>{resolved.label}</b> at only {(resolved.score * 100).toFixed(0)}%, which is noise, not a real signal. Nothing in the {graphCounts ? `${graphCounts.withLesson}-lesson library across ${graphCounts.subjects} subjects` : 'library'} is actually about this, so it is not shown as a match.</>
            ) : !entry?.chapter ? (
              <>
                Resolved to <b>{resolved.label}</b>{resolvedNode && <> in {subjectById.get(resolvedNode.subject)?.title ?? resolvedNode.subject}</>} at {(resolved.score * 100).toFixed(0)}%, highlighted in the graph.
                {contentLoading
                  ? ' Fetching its chapter...'
                  : contentFailed
                    ? ` ${contentFailed}`
                    : resolvedNode?.hasLesson
                      ? ' That lesson exists in the content library but failed to load.'
                      : ' No lesson exists for it yet. Honest gap, not a bug.'}
              </>
            ) : (
              <>
                Resolved to <b>{resolved.label}</b> at {(resolved.score * 100).toFixed(0)}% confidence
                {hasPath && pathIndex === 0 && (
                  <>, but that sits {path.length - 1} prerequisites deep, so you are starting at <b>{path[0].label}</b> and working up (step {pathIndex + 1} of {path.length})</>
                )}
                {hasPath && pathIndex > 0 && (
                  <>, its {path.length - 1}-step prerequisite ramp is shown below for context if you want to look back</>
                )}
                {belowThreshold && ', below our calibrated bar, shown honestly rather than faked as a confident match'}
                {matches && matches[0].conceptId !== resolved.conceptId && (
                  <> (top raw match was "{matches[0].label}" at {(matches[0].score * 100).toFixed(0)}%, but it has no content yet, so showing the next best real one)</>
                )}
              </>
            )}
          </span>
          {showPanels && (
            <button
              onClick={backToGraph}
              style={{ flexShrink: 0, fontSize: 11, padding: '4px 12px', borderRadius: 8, border: '1px solid rgba(255,255,255,0.18)', background: 'transparent', color: 'rgba(255,255,255,0.7)', cursor: 'pointer' }}
            >
              Back to full graph
            </button>
          )}
        </div>
      )}

      <div style={{ flex: 1, minHeight: 0, position: 'relative' }}>
        {/* Full-screen 3D graph: stays mounted always; dims under the panels
            after the highlight stage rather than disappearing, so the graph
            stays visibly alive behind and between the cards, then returns to
            full opacity for the next search's stage-one reveal. A real sim is
            its own opaque white page though, so dimming alone is not enough,
            the panels below are also inset with a real margin rather than
            spanning edge to edge, so a clear frame of graph always shows. */}
        <div style={{ position: 'absolute', inset: 0, zIndex: showPanels ? 0 : 2, opacity: showPanels ? 0.55 : 1, pointerEvents: showPanels ? 'none' : 'auto', transition: 'opacity 0.6s ease' }}>
          <iframe
            ref={graphIframeRef}
            title="concept-graph"
            src="/full-graph-viewer.html"
            onLoad={() => pushStudiedToGraph(studyLog)}
            style={{ width: '100%', height: '100%', border: 'none' }}
          />
        </div>

        {showPanels && chapter && resolved && (
          <div style={{ position: 'absolute', inset: '26px 20px 20px 20px', borderRadius: 18, zIndex: 1, display: 'flex', gap: 14, padding: '14px 16px 16px', background: 'transparent', boxShadow: '0 20px 60px rgba(0,0,0,0.55)' }}>
            {/* LEFT: chapter as a stack of cards, then the related-concepts navigator */}
            <div className="dul-col" style={{ flex: sim || generatedSim ? '0 0 30%' : '1 1 58%', minWidth: 320, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 14, paddingRight: 4, animation: 'dulRise 0.55s ease both' }}>
              {/* guided prerequisite path, only when there is a real ramp to
                  walk. Foundational on the left, the concept the query actually
                  resolved to on the right. */}
              {hasPath && (
                <div style={{ ...CARD, padding: '14px 16px', flexShrink: 0 }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap' }}>
                    <Eyebrow color="#58CC02">Your path to {path[path.length - 1].label}</Eyebrow>
                    <span style={{ fontSize: 10.5, color: contentLoading ? '#8BE85C' : 'rgba(255,255,255,0.4)' }}>
                      {contentLoading ? 'loading this step...' : `step ${pathIndex + 1} of ${path.length}`}
                    </span>
                  </div>
                  <p style={{ margin: '6px 0 10px', fontSize: 12, color: 'rgba(255,255,255,0.5)', lineHeight: 1.5 }}>
                    Built from the real prerequisite edges in the concept graph, foundational first. Every step has a written lesson, so any chip is clickable.
                  </p>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap' }}>
                    {path.map((step, i) => {
                      const current = i === pathIndex
                      const done = i < pathIndex
                      return (
                        <span key={step.conceptId} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                          {i > 0 && <span style={{ fontSize: 11, color: 'rgba(255,255,255,0.25)' }}>›</span>}
                          <button
                            onClick={() => goToStep(i)}
                            title={step.conceptId}
                            style={{
                              display: 'flex', alignItems: 'center', gap: 5, cursor: 'pointer',
                              fontSize: 11.5, fontWeight: current ? 700 : 500, padding: '5px 10px', borderRadius: 999,
                              border: `1px solid ${current ? '#58CC02' : done ? 'rgba(88,204,2,0.32)' : 'rgba(255,255,255,0.14)'}`,
                              background: current ? 'rgba(88,204,2,0.18)' : done ? 'rgba(88,204,2,0.06)' : 'rgba(255,255,255,0.03)',
                              color: current ? '#8BE85C' : done ? 'rgba(255,255,255,0.6)' : 'rgba(255,255,255,0.72)',
                            }}
                          >
                            <span style={{ fontSize: 9.5, opacity: 0.7 }}>{i + 1}</span>
                            {step.label}
                            {step.hasSim && <span style={{ fontSize: 8.5, fontWeight: 700, color: '#F0C060' }}>SIM</span>}
                            {isStudied(step.conceptId) && (
                              <span title="you have studied this before" style={{ fontSize: 8.5, fontWeight: 700, color: '#f2b84b' }}>✓ STUDIED</span>
                            )}
                          </button>
                        </span>
                      )
                    })}
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginTop: 12, flexWrap: 'wrap' }}>
                    <button
                      onClick={() => goToStep(pathIndex - 1)}
                      disabled={pathIndex === 0}
                      style={{ fontSize: 11.5, padding: '6px 12px', borderRadius: 8, border: '1px solid rgba(255,255,255,0.16)', background: 'transparent', color: pathIndex === 0 ? 'rgba(255,255,255,0.25)' : 'rgba(255,255,255,0.75)', cursor: pathIndex === 0 ? 'default' : 'pointer' }}
                    >
                      Back
                    </button>
                    {nextStep ? (
                      <button
                        onClick={() => goToStep(pathIndex + 1)}
                        style={{ fontSize: 12, fontWeight: 600, padding: '7px 14px', borderRadius: 8, border: 'none', background: '#58CC02', color: '#0a1a00', cursor: 'pointer' }}
                      >
                        Next concept: {nextStep.label} ›
                      </button>
                    ) : (
                      <span style={{ fontSize: 11.5, color: 'rgba(255,255,255,0.45)' }}>
                        Last step. This is what "{query || resolved.label}" actually resolved to.
                      </span>
                    )}
                  </div>
                </div>
              )}

              {/* chapter header + summary card */}
              <div style={{ ...CARD, padding: '18px 20px', flexShrink: 0 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
                  <Eyebrow color="#58CC02">Chapter{chapter.score != null ? ` · ${(chapter.score * 100).toFixed(0)}% match` : ''}</Eyebrow>
                  {usingSimplified && (
                    <span style={{ fontSize: 9.5, fontWeight: 700, letterSpacing: 0.6, color: '#5EC8F0', border: '1px solid rgba(94,200,240,0.5)', background: 'rgba(94,200,240,0.12)', borderRadius: 5, padding: '2px 7px' }}>
                      SIMPLIFIED
                    </span>
                  )}
                  {usingPersonalized && (
                    <span style={{ fontSize: 9.5, fontWeight: 700, letterSpacing: 0.6, color: '#F0C060', border: '1px solid rgba(240,192,96,0.5)', background: 'rgba(240,192,96,0.12)', borderRadius: 5, padding: '2px 7px' }}>
                      PERSONALIZED
                    </span>
                  )}
                  {simplifying && <span style={{ fontSize: 10.5, color: 'rgba(94,200,240,0.8)' }}>simplifying for your question...</span>}
                  {simplifiedBody && !usingPersonalized && (
                    <button
                      onClick={() => setShowSimplified(s => !s)}
                      style={{ marginLeft: 'auto', fontSize: 10.5, padding: '3px 10px', borderRadius: 6, border: '1px solid rgba(255,255,255,0.2)', background: 'transparent', color: 'rgba(255,255,255,0.7)', cursor: 'pointer' }}
                    >
                      {showSimplified ? 'show full original' : 'show simplified'}
                    </button>
                  )}
                </div>
                <div style={{ fontSize: 20, fontWeight: 700, lineHeight: 1.3, margin: '8px 0 8px' }}>{chapter.title}</div>
                <p style={{ margin: 0, fontSize: 13.5, lineHeight: 1.6, color: 'rgba(255,255,255,0.55)', fontStyle: 'italic' }}>{chapter.summary}</p>
                {usingSimplified && simplifyMeta && (
                  <p style={{ margin: '10px 0 0', fontSize: 11, lineHeight: 1.55, color: 'rgba(94,200,240,0.75)' }}>
                    Auto-shortened by {simplifyMeta.reductionPct}% for how you asked ("{searchedQuery}"), then independently checked to confirm no formula, number, or conclusion was lost. Toggle above for the full original.
                  </p>
                )}
                {!usingSimplified && !usingPersonalized && simplifyFailed && (
                  <p style={{ margin: '10px 0 0', fontSize: 11, lineHeight: 1.55, color: 'rgba(255,255,255,0.4)' }}>
                    Showing the full original chapter: the auto-simplified version was not used ({simplifyFailed}).
                  </p>
                )}
              </div>

              {/* personalize card */}
              <div style={{ ...CARD, padding: '14px 16px', flexShrink: 0 }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap' }}>
                  <Eyebrow color="#F0C060">Personalize this chapter</Eyebrow>
                  {personalizedBody && (
                    <button onClick={() => setShowPersonalized(s => !s)} style={{ fontSize: 11, padding: '3px 10px', borderRadius: 6, border: '1px solid rgba(255,255,255,0.2)', background: 'transparent', color: 'white', cursor: 'pointer' }}>
                      {showPersonalized ? 'show original' : 'show personalized'}
                    </button>
                  )}
                </div>
                <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap', marginTop: 10 }}>
                  <input
                    className="dul-input"
                    value={persona}
                    onChange={e => setPersona(e.target.value)}
                    placeholder="Describe the student..."
                    style={{ flex: 1, minWidth: 160, padding: '7px 10px', borderRadius: 8, border: '1px solid rgba(255,255,255,0.15)', background: 'rgba(255,255,255,0.04)', color: 'white', fontSize: 12 }}
                  />
                  <button
                    onClick={() => tryPersonalize(chapter.body)}
                    disabled={personalizing}
                    style={{ padding: '7px 14px', borderRadius: 8, border: 'none', background: '#F0C060', color: '#1a1400', fontWeight: 600, fontSize: 12, cursor: 'pointer', whiteSpace: 'nowrap' }}
                  >
                    {personalizing ? '...' : 'Personalize'}
                  </button>
                </div>
                {personalizeFailed && <p style={{ fontSize: 11, color: '#FF6B6B', margin: '8px 0 0' }}>{personalizeFailed}</p>}
                {showPersonalized && personalizedBody && (
                  <p style={{ fontSize: 11.5, color: '#F0C060', margin: '8px 0 0' }}>Personalized for: {persona}, same math, verified against the original.</p>
                )}
              </div>

              {/* content cards: paragraphs chunked in pairs */}
              {chunks.map((group, i) => (
                <div key={`${bodyVariant}-${i}`} style={{ ...CARD, padding: '16px 20px', flexShrink: 0 }}>
                  <Eyebrow color="rgba(255,255,255,0.35)">Part {i + 1} of {chunks.length}</Eyebrow>
                  {group.map((p, j) => (
                    <p key={j} style={{ margin: '10px 0 0', fontSize: 14, lineHeight: 1.7, color: 'rgba(255,255,255,0.85)' }}>{p}</p>
                  ))}
                </div>
              ))}

              {/* cement-understanding check: a real card in the stack, never a modal */}
              {checkQuestion && (
                <div style={{ ...CARD, padding: '16px 20px', flexShrink: 0 }}>
                  <Eyebrow color="#6366F1">Cement understanding</Eyebrow>
                  <div style={{ marginTop: 10 }}>
                    <ColdCheckPrompt
                      key={checkQuestion.id}
                      question={checkQuestion}
                      onResult={({ correct }) => {
                        setCheckResult(correct ? 'Recorded: correct, on your own.' : 'Recorded: missed it, flagged for review.')
                        if (activeConceptId) recordStudied(activeConceptId)
                      }}
                    />
                  </div>
                  {checkResult && <p style={{ fontSize: 12.5, color: 'rgba(255,255,255,0.6)', margin: '10px 0 0' }}>{checkResult}</p>}
                </div>
              )}

              {/* related concepts (ZPD) navigator */}
              <div style={{ ...CARD, padding: '16px 18px', flexShrink: 0 }}>
                <Eyebrow color="#6366F1">Related concepts</Eyebrow>
                <p style={{ margin: '6px 0 12px', fontSize: 12, color: 'rgba(255,255,255,0.5)', lineHeight: 1.5 }}>
                  Direct neighbors of {activeLabel || resolved.label} in the concept graph, natural next steps from here. Click one to jump to it.
                </p>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {neighbors.length === 0 && <p style={{ margin: 0, fontSize: 12, color: 'rgba(255,255,255,0.4)' }}>No graph neighbors found for this concept.</p>}
                  {neighbors.map(n => (
                    <button
                      key={n.id}
                      className="dul-neighbor"
                      onClick={() => { setQuery(n.label); void search(n.label) }}
                      style={{ display: 'flex', alignItems: 'center', gap: 10, textAlign: 'left', padding: '10px 12px', borderRadius: 10, border: '1px solid rgba(255,255,255,0.1)', background: 'rgba(255,255,255,0.03)', color: 'white', cursor: 'pointer', fontSize: 13 }}
                    >
                      <span style={{ flex: 1, minWidth: 0 }}>
                        {n.label}
                        <span style={{ display: 'block', fontSize: 10.5, color: 'rgba(255,255,255,0.35)', marginTop: 2 }}>{n.group}</span>
                      </span>
                      {isStudied(n.id) && <span title="you have studied this before" style={{ flexShrink: 0, fontSize: 10, fontWeight: 700, letterSpacing: 0.5, color: '#f2b84b', border: '1px solid rgba(242,184,75,0.4)', borderRadius: 5, padding: '2px 6px' }}>✓ STUDIED</span>}
                      {n.hasSim && <span style={{ flexShrink: 0, fontSize: 10, fontWeight: 700, letterSpacing: 0.5, color: '#F0C060', border: '1px solid rgba(240,192,96,0.4)', borderRadius: 5, padding: '2px 6px' }}>SIM</span>}
                      {!n.hasChapter && <span style={{ flexShrink: 0, fontSize: 10, color: 'rgba(255,255,255,0.35)' }}>no chapter yet</span>}
                      <span style={{ flexShrink: 0, display: 'flex', alignItems: 'center', gap: 6 }}>
                        <span style={{ width: 44, height: 4, borderRadius: 2, background: 'rgba(255,255,255,0.08)', overflow: 'hidden', display: 'inline-block' }}>
                          <span style={{ display: 'block', height: '100%', width: `${Math.round((n.weight / maxNeighborWeight) * 100)}%`, background: '#6366F1', borderRadius: 2 }} />
                        </span>
                        <span style={{ fontSize: 10.5, color: 'rgba(255,255,255,0.45)', width: 28, textAlign: 'right' }}>{(n.weight * 100).toFixed(0)}%</span>
                      </span>
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* RIGHT: the simulation is the star; when none exists, say so honestly */}
            {sim ? (
              <div style={{ ...CARD, flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', overflow: 'hidden', animation: 'dulRise 0.55s ease 0.08s both' }}>
                <div style={{ padding: '12px 18px', borderBottom: '1px solid rgba(255,255,255,0.07)', display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
                  <Eyebrow color="#F0C060">Interactive simulation</Eyebrow>
                  <span style={{ fontSize: 14, fontWeight: 600 }}>{sim.title}</span>
                  {sim.score != null && <span style={{ fontSize: 11, color: 'rgba(255,255,255,0.4)' }}>{(sim.score * 100).toFixed(0)}% match</span>}
                </div>
                <iframe title="sim" srcDoc={sim.html} style={{ flex: 1, border: 'none', background: 'white' }} sandbox="allow-scripts" />
              </div>
            ) : generatedSim ? (
              /* Same slot and same sandbox contract as a pre-written sim, but
                 badged so it is never mistaken for a human-reviewed one. */
              <div style={{ ...CARD, flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', overflow: 'hidden', animation: 'dulRise 0.55s ease both' }}>
                <div style={{ padding: '12px 18px', borderBottom: '1px solid rgba(255,255,255,0.07)', display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
                  <Eyebrow color="#A78BFA">Interactive simulation</Eyebrow>
                  <span style={{ fontSize: 14, fontWeight: 600 }}>{generatedSim.title}</span>
                  <span style={{ fontSize: 9.5, fontWeight: 700, letterSpacing: 0.6, color: '#A78BFA', border: '1px solid rgba(167,139,250,0.5)', background: 'rgba(167,139,250,0.12)', borderRadius: 5, padding: '2px 7px' }}>
                    AI GENERATED
                  </span>
                  <button
                    onClick={() => entry?.chapter && trySimGenerate(activeConceptId ?? '', entry.label, entry.chapter.body)}
                    disabled={simGenerating}
                    style={{ marginLeft: 'auto', fontSize: 10.5, padding: '3px 10px', borderRadius: 6, border: '1px solid rgba(255,255,255,0.2)', background: 'transparent', color: 'rgba(255,255,255,0.7)', cursor: simGenerating ? 'default' : 'pointer' }}
                  >
                    {simGenerating ? 'generating...' : 'regenerate'}
                  </button>
                  <div style={{ flexBasis: '100%', fontSize: 11, color: 'rgba(255,255,255,0.4)', lineHeight: 1.5 }}>
                    Generated live for this concept, then independently reviewed by a second model for correctness and safety before being shown. Not human reviewed.
                    {generatedSim.reviewSummary ? ` Reviewer said: ${generatedSim.reviewSummary}` : ''}
                  </div>
                </div>
                <iframe title="generated-sim" srcDoc={generatedSim.html} style={{ flex: 1, border: 'none', background: 'white' }} sandbox="allow-scripts" />
              </div>
            ) : (
              <div style={{ ...CARD, border: '1.5px dashed rgba(255,255,255,0.14)', boxShadow: 'none', background: 'rgba(255,255,255,0.015)', flex: '0 0 38%', minWidth: 300, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center', padding: '32px 36px', gap: 14, animation: 'dulRise 0.55s ease 0.08s both' }}>
                <svg width="52" height="52" viewBox="0 0 24 24" fill="none" stroke="rgba(255,255,255,0.28)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                  <rect x="2.5" y="3.5" width="19" height="13" rx="2" />
                  <path d="M8 20.5h8M12 16.5v4" />
                  <path d="M8.5 8.5h7M8.5 11.5h4" strokeDasharray="2 2.5" />
                </svg>
                <div style={{ fontSize: 16, fontWeight: 700, color: 'rgba(255,255,255,0.85)' }}>No simulation exists yet for this concept</div>
                <p style={{ margin: 0, fontSize: 13, lineHeight: 1.65, color: 'rgba(255,255,255,0.5)', maxWidth: 340 }}>
                  {graphCounts ? `Only ${graphCounts.withSim} of ${graphCounts.nodes} concepts in the library have an interactive sim so far` : 'Most concepts have no interactive sim yet'}, and {activeLabel || resolved.label} isn't one of them yet. That's a real content gap we're closing, not a loading error.
                </p>

                <button
                  onClick={() => entry?.chapter && trySimGenerate(activeConceptId ?? '', entry.label, entry.chapter.body)}
                  disabled={simGenerating || !entry?.chapter}
                  style={{ padding: '10px 20px', borderRadius: 10, border: 'none', background: simGenerating ? 'rgba(167,139,250,0.35)' : '#A78BFA', color: '#140a2e', fontWeight: 700, fontSize: 13, cursor: simGenerating ? 'default' : 'pointer' }}
                >
                  {simGenerating ? 'Generating and reviewing...' : 'Generate a sim for this'}
                </button>

                {simGenerating ? (
                  <p style={{ margin: 0, fontSize: 11.5, lineHeight: 1.6, color: 'rgba(167,139,250,0.85)', maxWidth: 340 }}>
                    Writing an interactive sim for {activeLabel || resolved.label}, then having a second, different model independently review it for correctness and safety before you see it. This usually takes five to fifteen seconds. If the review rejects it, you will be told why instead of being shown it anyway.
                  </p>
                ) : simGenFailed ? (
                  <p style={{ margin: 0, fontSize: 11.5, lineHeight: 1.6, color: '#FF6B6B', maxWidth: 340 }}>{simGenFailed}</p>
                ) : (
                  <p style={{ margin: 0, fontSize: 11.5, lineHeight: 1.6, color: 'rgba(255,255,255,0.35)', maxWidth: 340 }}>
                    A generated sim is clearly badged as AI generated and is never shown unless a second model passes it. Related concepts tagged <span style={{ color: '#F0C060', fontWeight: 700 }}>SIM</span> below the chapter have a human-reviewed one.
                  </p>
                )}
              </div>
            )}
          </div>
        )}
      </div>

      <div style={{ flexShrink: 0, padding: '14px 20px', borderTop: '1px solid rgba(255,255,255,0.08)', display: 'flex', gap: 10, background: '#0A0A0F' }}>
        <input
          className="dul-input"
          value={query}
          onChange={e => setQuery(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && search()}
          placeholder="Ask anything, or paste a homework question..."
          style={{ flex: 1, padding: '12px 16px', borderRadius: 12, border: '1px solid rgba(255,255,255,0.15)', background: 'rgba(255,255,255,0.04)', color: 'white', fontSize: 14 }}
        />
        <button onClick={() => void search()} disabled={loading} style={{ padding: '12px 26px', borderRadius: 12, border: 'none', background: '#6366F1', color: 'white', fontWeight: 600, cursor: 'pointer' }}>
          {loading ? '...' : 'Search'}
        </button>
        {studiedIds.length > 0 && (
          <span title={studiedIds.join(', ')} style={{ alignSelf: 'center', fontSize: 11.5, color: '#f2b84b', whiteSpace: 'nowrap' }}>
            ✓ {studiedIds.length} studied
          </span>
        )}
        {err && <p style={{ color: '#FF6B6B', fontSize: 13, alignSelf: 'center', marginLeft: 8 }}>{err}</p>}
      </div>

      {/* live question-generation status: unobtrusive chip, never a modal */}
      {showPanels && (generating || (generateFailed && !checkQuestion)) && (
        <div style={{ ...CARD, position: 'fixed', right: 20, bottom: 88, zIndex: 40, maxWidth: 380, padding: '10px 14px', fontSize: 12, lineHeight: 1.5, color: generating ? 'rgba(255,255,255,0.7)' : '#F0C060' }}>
          {generating
            ? 'Bank has nothing here, generating a check question live, then independently re-solving it...'
            : generateFailed}
        </div>
      )}

    </div>
  )
}
