/**
 * Diagnostic.tsx — goals + concept confidence + probe questions (kickstarts the engine).
 *
 * Reached from the kitchen world ("Let Nox Cook"), not immediately after login.
 * Flow: login → kitchen world → Let Nox Cook → this page → dashboard.
 *   - goals          → stored on users/{uid}.goals
 *   - confidence      → POST /seed-assessment (hard|kinda|easy per concept)
 *   - probe answers   → POST /record-outcomes (C4 hide-correctness, C5 format tag)
 *   - complete        → markDiagnosticComplete (diagnosticCompleted: true) + goals
 *
 * The spec/questions come from data/actDiagnostic.json, generated by
 * ml/scripts/build_act_diagnostic.py off the annotated ACT bank.
 */

import { useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { doc, setDoc } from 'firebase/firestore'
import { db } from '../firebase'
import { useUser } from '../App'
import { seedAssessment, recordOutcomes, conceptLabel } from '../lib/mlApi'
import { markDiagnosticComplete } from '../lib/practiceState'
import { invalidateKnowledgeGraph } from '../lib/graphCache'
import { toOntologyId } from '../lib/conceptMap'
import type { Confidence } from '../lib/bridgePractice'
import type { FormatId } from '../lib/questionBank'
import spec from '../data/actDiagnostic.json'
import s from './Diagnostic.module.css'

interface ConfConcept { concept_id: string; name: string; act_high_priority: boolean }
interface ScalePoint { value: number; label: string }
interface Probe {
  question_id: string
  concept_id: string
  stem: string
  choices: Record<string, string>
  correct_answer: string
  skill_gap_if_wrong: string
  format?: FormatId
  level?: 1 | 2 | 3
}

const EXAM = 'ACT'

/** Map kitchen-world self-report scale → gap-scan confidence bucket for /seed-assessment. */
function diagnosticScaleToConfidence(value: number): Confidence {
  if (value <= 0.3) return 'hard'
  if (value <= 0.6) return 'kinda'
  return 'easy'
}

function buildConfidenceMap(scale: Record<string, number>): Record<string, Confidence> {
  const out: Record<string, Confidence> = {}
  for (const [conceptId, value] of Object.entries(scale)) {
    out[toOntologyId(conceptId)] = diagnosticScaleToConfidence(value)
  }
  return out
}

type Step = 'intro' | 'goals' | 'confidence' | 'probes' | 'done'

export default function Diagnostic() {
  const user = useUser()
  const navigate = useNavigate()
  const concepts = (spec as { confidence_step: { concepts: ConfConcept[] } }).confidence_step.concepts
  const scale = (spec as { confidence_step: { scale: ScalePoint[] } }).confidence_step.scale
  const probes = (spec as { probe_step: { questions: Probe[] } }).probe_step.questions
  const presets = (spec as { goals_step: { presets: string[] } }).goals_step.presets

  const [step, setStep] = useState<Step>('intro')
  const [goalTags, setGoalTags] = useState<string[]>([])
  const [goalText, setGoalText] = useState('')
  const [confidence, setConfidence] = useState<Record<string, number>>({})
  const [probeIdx, setProbeIdx] = useState(0)
  const [picked, setPicked] = useState<string | null>(null)
  const [questionStart, setQuestionStart] = useState(Date.now())
  const [saving, setSaving] = useState(false)
  const advanceTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  const progress = useMemo(() => {
    const order: Step[] = ['intro', 'goals', 'confidence', 'probes', 'done']
    return (order.indexOf(step) / (order.length - 1)) * 100
  }, [step])

  function toggleGoal(tag: string) {
    setGoalTags(prev => (prev.includes(tag) ? prev.filter(t => t !== tag) : [...prev, tag]))
  }

  function setConf(conceptId: string, value: number) {
    setConfidence(prev => ({ ...prev, [conceptId]: value }))
  }

  async function finishConfidence() {
    const assessment = buildConfidenceMap(confidence)
    await seedAssessment(user.uid, assessment)
    invalidateKnowledgeGraph(user.uid)
    setQuestionStart(Date.now())
    setStep('probes')
  }

  function advanceProbe() {
    const nextIdx = probeIdx + 1
    if (nextIdx < probes.length) {
      setProbeIdx(nextIdx)
      setPicked(null)
      setQuestionStart(Date.now())
    } else {
      void complete()
    }
  }

  /** C4 — record probe outcome via /record-outcomes; never reveal right/wrong. */
  async function answerProbe(choiceKey: string) {
    if (picked) return
    setPicked(choiceKey)
    const probe = probes[probeIdx]
    const chosen = probe.choices[choiceKey] ?? ''
    const correct = normalize(chosen) === normalize(probe.correct_answer)

    void recordOutcomes(user.uid, [{
      conceptId: toOntologyId(probe.concept_id),
      score: correct ? 1 : 0,
      level: probe.level ?? 2,
      questionId: probe.question_id,
      formatId: probe.format,
    }])
    invalidateKnowledgeGraph(user.uid)

    if (advanceTimer.current) clearTimeout(advanceTimer.current)
    advanceTimer.current = setTimeout(advanceProbe, 400)
  }

  function skipProbe() {
    if (advanceTimer.current) clearTimeout(advanceTimer.current)
    advanceProbe()
  }

  async function complete() {
    setSaving(true)
    setStep('done')
    const goals = { tags: goalTags, text: goalText.trim() }
    const confidenceMap = buildConfidenceMap(confidence)
    try {
      await setDoc(
        doc(db, 'users', user.uid),
        {
          goals,
          diagnosticCompletedAt: new Date().toISOString(),
          diagnosticVersion: (spec as { version?: string }).version,
        },
        { merge: true },
      )
    } catch {
      /* non-blocking */
    }
    await markDiagnosticComplete(user.uid, { exam: EXAM, confidenceMap })
    invalidateKnowledgeGraph(user.uid)
    setSaving(false)
  }

  function goToDashboard() {
    navigate('/dashboard', { replace: true })
  }

  return (
    <div className={s.page}>
      <div className={s.bar}><div className={s.barFill} style={{ width: `${progress}%` }} /></div>
      <div className={s.shell}>

        {step === 'intro' && (
          <section className={s.card}>
            <p className={s.kicker}>MindCraft diagnostic</p>
            <h1 className={s.title}>{(spec as { intro: { title: string } }).intro.title}</h1>
            <p className={s.body}>{(spec as { intro: { body: string } }).intro.body}</p>
            <button className={s.primary} onClick={() => setStep('goals')}>Start</button>
          </section>
        )}

        {step === 'goals' && (
          <section className={s.card}>
            <h2 className={s.h2}>{(spec as { goals_step: { prompt: string } }).goals_step.prompt}</h2>
            <div className={s.tags}>
              {presets.map(p => (
                <button
                  key={p}
                  className={`${s.tag} ${goalTags.includes(p) ? s.tagOn : ''}`}
                  onClick={() => toggleGoal(p)}
                >{p}</button>
              ))}
            </div>
            <textarea
              className={s.textarea}
              placeholder="Anything specific? (optional)"
              value={goalText}
              onChange={e => setGoalText(e.target.value)}
              rows={3}
            />
            <button
              className={s.primary}
              disabled={goalTags.length === 0 && !goalText.trim()}
              onClick={() => setStep('confidence')}
            >Next</button>
          </section>
        )}

        {step === 'confidence' && (
          <section className={s.card}>
            <h2 className={s.h2}>{(spec as { confidence_step: { prompt: string } }).confidence_step.prompt}</h2>
            <p className={s.note}>{(spec as { confidence_step: { note: string } }).confidence_step.note}</p>
            <div className={s.confList}>
              {concepts.map(c => (
                <div key={c.concept_id} className={s.confRow}>
                  <div className={s.confName}>
                    {c.name}
                    {c.act_high_priority && <span className={s.pill}>ACT core</span>}
                  </div>
                  <div className={s.scale}>
                    {scale.map(sp => (
                      <button
                        key={sp.value}
                        className={`${s.scaleBtn} ${confidence[c.concept_id] === sp.value ? s.scaleOn : ''}`}
                        onClick={() => setConf(c.concept_id, sp.value)}
                      >{sp.label}</button>
                    ))}
                  </div>
                </div>
              ))}
            </div>
            <button
              className={s.primary}
              disabled={Object.keys(confidence).length < concepts.length}
              onClick={() => void finishConfidence()}
            >Next</button>
          </section>
        )}

        {step === 'probes' && probes[probeIdx] && (
          <section className={s.card}>
            <p className={s.kicker}>
              {conceptLabel(probes[probeIdx].concept_id)} · {probeIdx + 1}/{probes.length}
            </p>
            <h2 className={s.stem}>{probes[probeIdx].stem}</h2>
            <div className={s.choices}>
              {Object.entries(probes[probeIdx].choices).map(([key, val]) => (
                <button
                  key={key}
                  className={`${s.choice} ${picked === key ? s.selected : ''}`}
                  disabled={!!picked}
                  onClick={() => void answerProbe(key)}
                >
                  <span className={s.choiceKey}>{key}</span>{val}
                </button>
              ))}
            </div>
            <button className={s.ghost} onClick={skipProbe} disabled={!!picked}>Skip — not sure</button>
          </section>
        )}

        {step === 'done' && (
          <section className={s.card}>
            <h1 className={s.title}>You're mapped.</h1>
            <p className={s.body}>
              Nox now has a starting picture of your strengths and gaps. The more you
              practice, the sharper your learning world gets.
            </p>
            <button className={s.primary} onClick={goToDashboard} disabled={saving}>
              {saving ? 'Saving…' : 'Go to my dashboard'}
            </button>
          </section>
        )}
      </div>
    </div>
  )
}

function normalize(value: string): string {
  return (value || '')
    .toLowerCase()
    .replace(/[\s−–—]+/g, '')
    .replace(/[^\w/().+-]/g, '')
}
