/**
 * Diagnostic.tsx — goals + concept confidence + probe questions (kickstarts the engine).
 *
 * Reached from the kitchen world ("Let Nox Cook"), not immediately after login.
 * Flow: login → kitchen world → Let Nox Cook → this page → dashboard.
 *   - goals          → stored on users/{uid}.goals
 *   - confidence      → POST /learning-event (confidence_report, outcome=null)
 *   - probe answers   → POST /learning-event (answer_submitted, outcome 1/0)
 *   - complete        → POST /learning-event (diagnostic_complete) + users/{uid}.diagnosticCompletedAt
 *
 * The spec/questions come from data/actDiagnostic.json, generated by
 * ml/scripts/build_act_diagnostic.py off the annotated ACT bank.
 */

import { useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { doc, setDoc } from 'firebase/firestore'
import { db } from '../firebase'
import { useUser } from '../App'
import { sendLearningEvent, conceptLabel } from '../lib/mlApi'
import spec from '../data/actDiagnostic.json'
import s from './Diagnostic.module.css'

interface ConfConcept { concept_id: string; name: string; act_high_priority: boolean }
interface ScalePoint { value: number; label: string }
interface Probe {
  question_id: string
  concept_id: string
  stem: string
  choices: Record<string, string>
  correct_answer: string
  skill_gap_if_wrong: string
}

const SUBJECT = (spec as any).subject_id ?? 'math'

const ENCOURAGEMENT = [
  "You're doing great — keep going!",
  'Every answer helps Jesse cook up your path.',
  'Nice work — one question at a time.',
  "Love the effort — Jesse's taking notes.",
  "Keep it up — you're building something good here.",
]

type Step = 'intro' | 'goals' | 'confidence' | 'probes' | 'done'

export default function Diagnostic() {
  const user = useUser()
  const navigate = useNavigate()
  const concepts = (spec as any).confidence_step.concepts as ConfConcept[]
  const scale = (spec as any).confidence_step.scale as ScalePoint[]
  const probes = (spec as any).probe_step.questions as Probe[]
  const presets = (spec as any).goals_step.presets as string[]

  const [step, setStep] = useState<Step>('intro')
  const [goalTags, setGoalTags] = useState<string[]>([])
  const [goalText, setGoalText] = useState('')
  const [confidence, setConfidence] = useState<Record<string, number>>({})
  const [probeIdx, setProbeIdx] = useState(0)
  const [picked, setPicked] = useState<string | null>(null)
  const [correctCount, setCorrectCount] = useState(0)
  const [questionStart, setQuestionStart] = useState(Date.now())
  const [saving, setSaving] = useState(false)
  const advanceTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  const progress = useMemo(() => {
    const order: Step[] = ['intro', 'goals', 'confidence', 'probes', 'done']
    return (order.indexOf(step) / (order.length - 1)) * 100
  }, [step])

  function toggleGoal(tag: string) {
    setGoalTags(prev => (prev.includes(tag) ? prev.filter(t => t !== tag) : [...prev, tag]))
  }

  function setConf(conceptId: string, value: number) {
    setConfidence(prev => ({ ...prev, [conceptId]: value }))
  }

  // ── confidence → emit one event per rated concept, then move to probes ──
  async function finishConfidence() {
    await Promise.allSettled(
      Object.entries(confidence).map(([conceptId, value]) =>
        sendLearningEvent({
          studentId: user.uid,
          subjectId: SUBJECT,
          conceptId,
          eventType: 'confidence_report',
          outcome: null,
          source: 'diagnostic',
          metadata: { confidence: value, step: 'confidence' },
        }),
      ),
    )
    setQuestionStart(Date.now())
    setStep('probes')
  }

  // ── probe answer → emit answer_submitted, advance ──
  async function answerProbe(choiceKey: string) {
    if (picked) return
    setPicked(choiceKey)
    const probe = probes[probeIdx]
    const chosen = probe.choices[choiceKey] ?? ''
    const correct = normalize(chosen) === normalize(probe.correct_answer)
    if (correct) setCorrectCount(c => c + 1)

    await sendLearningEvent({
      studentId: user.uid,
      subjectId: SUBJECT,
      conceptId: probe.concept_id,
      eventType: 'answer_submitted',
      outcome: correct ? 1.0 : 0.0,
      durationMs: Date.now() - questionStart,
      source: 'diagnostic',
      metadata: { question_id: probe.question_id, selected: choiceKey, step: 'probe' },
    })

    if (advanceTimer.current) clearTimeout(advanceTimer.current)
    const nextIdx = probeIdx + 1
    advanceTimer.current = setTimeout(() => {
      if (nextIdx < probes.length) {
        setProbeIdx(nextIdx)
        setPicked(null)
        setQuestionStart(Date.now())
      } else {
        complete()
      }
    }, 2000)
  }

  function skipProbe() {
    if (probeIdx + 1 < probes.length) {
      setProbeIdx(probeIdx + 1)
      setPicked(null)
      setQuestionStart(Date.now())
    } else {
      complete()
    }
  }

  // ── done → persist goals + completion, mark engine kickstarted, go to world ──
  async function complete() {
    setSaving(true)
    setStep('done')
    const goals = { tags: goalTags, text: goalText.trim() }
    try {
      await setDoc(
        doc(db, 'users', user.uid),
        {
          goals,
          diagnosticCompletedAt: new Date().toISOString(),
          diagnosticVersion: (spec as any).version,
        },
        { merge: true },
      )
    } catch {
      /* non-blocking */
    }
    await sendLearningEvent({
      studentId: user.uid,
      subjectId: SUBJECT,
      conceptId: 'diagnostic',
      eventType: 'diagnostic_complete',
      source: 'diagnostic',
      metadata: {
        concepts_seen: concepts.length,
        probes_answered: probes.length,
        correct: correctCount,
        goals,
      },
    })
    setSaving(false)
  }

  function goToDashboard() {
    navigate('/dashboard', { replace: true })
  }

  return (
    <div className={s.page}>
      <div className={s.bar}><div className={s.barFill} style={{ width: `${progress}%` }} /></div>
      <div className={s.shell}>

        {step === 'intro' && (
          <section className={s.card}>
            <p className={s.kicker}>MindCraft diagnostic</p>
            <h1 className={s.title}>{(spec as any).intro.title}</h1>
            <p className={s.body}>{(spec as any).intro.body}</p>
            <button className={s.primary} onClick={() => setStep('goals')}>Start</button>
          </section>
        )}

        {step === 'goals' && (
          <section className={s.card}>
            <h2 className={s.h2}>{(spec as any).goals_step.prompt}</h2>
            <div className={s.tags}>
              {presets.map(p => (
                <button
                  key={p}
                  className={`${s.tag} ${goalTags.includes(p) ? s.tagOn : ''}`}
                  onClick={() => toggleGoal(p)}
                >{p}</button>
              ))}
            </div>
            <textarea
              className={s.textarea}
              placeholder="Anything specific? (optional)"
              value={goalText}
              onChange={e => setGoalText(e.target.value)}
              rows={3}
            />
            <button
              className={s.primary}
              disabled={goalTags.length === 0 && !goalText.trim()}
              onClick={() => setStep('confidence')}
            >Next</button>
          </section>
        )}

        {step === 'confidence' && (
          <section className={s.card}>
            <h2 className={s.h2}>{(spec as any).confidence_step.prompt}</h2>
            <p className={s.note}>{(spec as any).confidence_step.note}</p>
            <div className={s.confList}>
              {concepts.map(c => (
                <div key={c.concept_id} className={s.confRow}>
                  <div className={s.confName}>
                    {c.name}
                    {c.act_high_priority && <span className={s.pill}>ACT core</span>}
                  </div>
                  <div className={s.scale}>
                    {scale.map(sp => (
                      <button
                        key={sp.value}
                        className={`${s.scaleBtn} ${confidence[c.concept_id] === sp.value ? s.scaleOn : ''}`}
                        onClick={() => setConf(c.concept_id, sp.value)}
                      >{sp.label}</button>
                    ))}
                  </div>
                </div>
              ))}
            </div>
            <button
              className={s.primary}
              disabled={Object.keys(confidence).length < concepts.length}
              onClick={finishConfidence}
            >Next</button>
          </section>
        )}

        {step === 'probes' && probes[probeIdx] && (
          <section className={s.card}>
            <p className={s.kicker}>
              {conceptLabel(probes[probeIdx].concept_id)} · {probeIdx + 1}/{probes.length}
            </p>
            <h2 className={s.stem}>{probes[probeIdx].stem}</h2>
            <div className={s.choices}>
              {Object.entries(probes[probeIdx].choices).map(([key, val]) => {
                const isCorrect = normalize(val) === normalize(probes[probeIdx].correct_answer)
                const state = !picked ? '' : key === picked ? (isCorrect ? s.right : s.wrong) : (isCorrect ? s.right : '')
                return (
                  <button key={key} className={`${s.choice} ${state}`} disabled={!!picked} onClick={() => answerProbe(key)}>
                    <span className={s.choiceKey}>{key}</span>{val}
                  </button>
                )
              })}
            </div>
            <button className={s.ghost} onClick={skipProbe} disabled={!!picked}>Skip — not sure</button>
            {picked && (
              <p className={s.feedback}>{ENCOURAGEMENT[probeIdx % ENCOURAGEMENT.length]}</p>
            )}
          </section>
        )}

        {step === 'done' && (
          <section className={s.card}>
            <h1 className={s.title}>You're mapped.</h1>
            <p className={s.body}>
              Nox now has a starting picture of your strengths and gaps. The more you
              practice, the sharper your learning world gets.
            </p>
            <button className={s.primary} onClick={goToDashboard} disabled={saving}>
              {saving ? 'Saving…' : 'Go to my dashboard'}
            </button>
          </section>
        )}
      </div>
    </div>
  )
}

function normalize(value: string): string {
  return (value || '')
    .toLowerCase()
    .replace(/[\s−–—]+/g, '')
    .replace(/[^\w/().+-]/g, '')
}
