import type { RefObject } from 'react'
import type { ConceptMatch, ConceptSim, GeneratedSim } from '../../lib/conceptLibrary'
import MaterialsPanel from './MaterialsPanel'
import { BORDER_SOFT, CARD, Eyebrow, TEXT_FAINT, TEXT_PRIMARY, type LibraryCounts, type MaterialsState } from './shared'

export interface RightColumnProps {
  hasSimContent: boolean
  effectiveTab: 'sim' | 'materials'
  onSetRightTab: (tab: 'sim' | 'materials') => void
  materials: MaterialsState | null
  sim: ConceptSim | null
  generatedSim: GeneratedSim | null
  counts: LibraryCounts | null
  activeLabel: string
  resolved: ConceptMatch
  simGenerating: boolean
  simGenStatus: string
  simGenFailed: string
  onRunSimGeneration: () => void
  materialsBusy: string
  materialsError: string
  selectedQ: number | null
  materialsFileRef: RefObject<HTMLInputElement>
  materialsAccept: string
  onFileChosen: (file: File) => void
  onSelectQuestion: (i: number) => void
  onClearMaterials: () => void
}

/** The right-hand column: the sim/materials tab switcher, the interactive
 * sim (real or AI generated), and the materials upload panel. Purely
 * presentational, every piece of state and every handler lives in
 * Learn.tsx. */
export default function RightColumn({
  hasSimContent, effectiveTab, onSetRightTab, materials, sim, generatedSim, counts,
  activeLabel, resolved, simGenerating, simGenStatus, simGenFailed, onRunSimGeneration,
  materialsBusy, materialsError, selectedQ, materialsFileRef, materialsAccept,
  onFileChosen, onSelectQuestion, onClearMaterials,
}: RightColumnProps) {
  return (
    <div style={{ flex: hasSimContent ? '1 1 auto' : '0 0 38%', minWidth: 300, display: 'flex', flexDirection: 'column', gap: 0, animation: 'lrnRise 0.55s ease 0.08s both' }}>
      {hasSimContent && (
        <div style={{ display: 'flex', gap: 8, marginBottom: 10, flexShrink: 0 }}>
          {(['sim', 'materials'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => onSetRightTab(tab)}
              style={{
                fontSize: 12.5, fontWeight: 600, padding: '6px 14px', borderRadius: 999, cursor: 'pointer',
                border: `1px solid ${effectiveTab === tab ? 'rgba(129,140,248,0.6)' : 'rgba(205,215,238,0.18)'}`,
                background: effectiveTab === tab ? '#2A3054' : 'rgba(15,20,36,0.85)',
                color: effectiveTab === tab ? '#B4BCF9' : TEXT_FAINT,
              }}
            >
              {tab === 'sim' ? 'Simulation' : `Your materials${materials ? ` (${materials.questions.length})` : ''}`}
            </button>
          ))}
        </div>
      )}

      {hasSimContent && effectiveTab === 'sim' ? (
        sim ? (
          <div style={{ ...CARD, flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
            <div style={{ padding: '12px 18px', borderBottom: BORDER_SOFT, display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
              <Eyebrow color="#F0C060">Interactive simulation</Eyebrow>
              <span style={{ fontSize: 14.5, fontWeight: 600 }}>{sim.title}</span>
              {sim.sourceRepo && <span style={{ fontSize: 11.5, color: TEXT_FAINT }}>{sim.sourceRepo}</span>}
            </div>
            <iframe title="sim" srcDoc={sim.html} style={{ flex: 1, border: 'none', background: 'white' }} sandbox="allow-scripts" />
          </div>
        ) : generatedSim ? (
          <div style={{ ...CARD, flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
            <div style={{ padding: '12px 18px', borderBottom: BORDER_SOFT, display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
              <Eyebrow color="#A78BFA">Interactive simulation</Eyebrow>
              <span style={{ fontSize: 14.5, fontWeight: 600 }}>{generatedSim.title}</span>
              <span style={{ fontSize: 10, fontWeight: 700, letterSpacing: 0.6, color: '#A78BFA', border: '1px solid rgba(167,139,250,0.5)', background: 'rgba(167,139,250,0.12)', borderRadius: 6, padding: '2px 8px' }}>
                AI GENERATED
              </span>
              {generatedSim.cached && <span style={{ fontSize: 10.5, color: TEXT_FAINT }}>reused from the library, not regenerated</span>}
              <div style={{ flexBasis: '100%', fontSize: 11.5, color: TEXT_FAINT, lineHeight: 1.5, marginTop: 4 }}>
                Generated by the MicroSim pipeline and only shown because it passed the structural rubric and the visual quality gate. Not human reviewed.
                {typeof generatedSim.qualityGateScore === 'number' ? ` Gate score ${generatedSim.qualityGateScore}.` : ''}
              </div>
            </div>
            <iframe title="generated-sim" srcDoc={generatedSim.html} style={{ flex: 1, border: 'none', background: 'white' }} sandbox="allow-scripts" />
          </div>
        ) : null
      ) : (
        <div className="lrn-col" style={{ ...CARD, flex: 1, minHeight: 0, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 14, padding: '20px 22px' }}>
          {!hasSimContent && (
            <div style={{ borderBottom: BORDER_SOFT, paddingBottom: 16 }}>
              <Eyebrow color="#A78BFA">Simulation</Eyebrow>
              <div style={{ fontSize: 15.5, fontWeight: 700, margin: '8px 0 6px', color: TEXT_PRIMARY }}>No simulation exists yet for this concept</div>
              <p style={{ margin: 0, fontSize: 13, lineHeight: 1.6, color: TEXT_FAINT }}>
                {counts ? `Only ${counts.withSim} of ${counts.nodes} concepts in the library have a pre-built interactive sim so far` : 'Most concepts have no pre-built interactive sim yet'}, and {activeLabel || resolved.label} isn't one of them. That's a real content gap we're closing, not a loading error.
              </p>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginTop: 12, flexWrap: 'wrap' }}>
                <button
                  onClick={onRunSimGeneration}
                  disabled={simGenerating}
                  style={{ padding: '9px 18px', borderRadius: 10, border: 'none', background: simGenerating ? 'rgba(167,139,250,0.35)' : '#A78BFA', color: '#140a2e', fontWeight: 700, fontSize: 13, cursor: simGenerating ? 'default' : 'pointer' }}
                >
                  {simGenerating ? 'Generating and reviewing...' : 'Generate a sim for this'}
                </button>
              </div>
              {simGenerating ? (
                <p style={{ margin: '10px 0 0', fontSize: 12, lineHeight: 1.6, color: 'rgba(167,139,250,0.85)' }}>
                  {simGenStatus || 'Starting...'} The pipeline writes the sim, renders it headlessly, scores it against a structural rubric, then runs a visual quality gate. Nothing is shown unless the whole gate passes, and if it fails you will be told why. This usually takes under two minutes.
                </p>
              ) : simGenFailed ? (
                <p style={{ margin: '10px 0 0', fontSize: 12, lineHeight: 1.6, color: '#FF7B7B' }}>{simGenFailed}</p>
              ) : (
                <p style={{ margin: '10px 0 0', fontSize: 12, lineHeight: 1.6, color: TEXT_FAINT }}>
                  A generated sim is clearly badged AI GENERATED and is never shown unless it passes the quality gate. Generation spends from a shared monthly budget, so it is a deliberate button, not automatic.
                </p>
              )}
            </div>
          )}

          <MaterialsPanel
            materials={materials}
            materialsBusy={materialsBusy}
            materialsError={materialsError}
            selectedQ={selectedQ}
            materialsFileRef={materialsFileRef}
            materialsAccept={materialsAccept}
            onFileChosen={onFileChosen}
            onSelectQuestion={onSelectQuestion}
            onClearMaterials={onClearMaterials}
          />
        </div>
      )}
    </div>
  )
}
