/**
 * DiagnosticArt.tsx — hand-authored inline SVG illustrations for Diagnostic.tsx.
 *
 * Same "field notebook sketch" style system as the 26 concept-art plates in
 * app/src/assets/canvas/generated/story-*.svg (see
 * app/scripts/generateConceptArtSvg.mjs for the full palette/linework
 * reasoning): warm parchment background, ink-brown linework, one navy accent,
 * one gold accent. Reused here — not regenerated by that script, since these
 * are UI chrome (diagnostic onboarding), not per-concept story art — so the
 * consolidated diagnostic reads as the same notebook, not a third visual
 * style. No image-generation model involved; every path below is hand-drawn.
 *
 * Kept intentionally restrained per BRAND_BOOK.md: no cartoon mascots, no
 * cutesy faces — objects only (a desk, a clock, a calendar, an hourglass),
 * the same register as the rest of the app's line art.
 */

const INK = '#33230f'
const PARCH_A = '#fbf3e2'
const PARCH_B = '#eddab3'
const PARCH_C = '#e2c793'
const NAVY = '#1d3a8a'
const GOLD = '#c99a3a'
const GOLD_LT = '#e7c877'

/** Warm study-desk scene for the diagnostic's intro step — candle, open
 *  notebook, a small plant. Same cozy-desk identity as the notebook cover
 *  (mindcraft-cover-hero.jpg), redrawn in the app's own ink-line family
 *  since that cover art is a photo plate, not something this pass can
 *  regenerate (Higgsfield is at 0 credits). */
export function DeskArt({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 400 260" className={className} role="img" aria-hidden="true">
      <defs>
        <linearGradient id="diagDeskBg" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor={PARCH_A} />
          <stop offset="1" stopColor={PARCH_C} />
        </linearGradient>
      </defs>
      <rect x="0" y="0" width="400" height="260" rx="18" fill="url(#diagDeskBg)" />

      {/* window glow */}
      <path d="M40 30 L40 90 A50 50 0 0 1 140 90 L140 30 Z" fill={PARCH_A} stroke={INK} strokeWidth="3" opacity="0.75" />
      <line x1="90" y1="30" x2="90" y2="90" stroke={INK} strokeWidth="1.75" opacity="0.4" />

      {/* desk surface */}
      <rect x="0" y="190" width="400" height="70" fill={PARCH_C} opacity="0.55" />
      <line x1="0" y1="190" x2="400" y2="190" stroke={INK} strokeWidth="3" opacity="0.35" />

      {/* small plant, left */}
      <g transform="translate(56 178)">
        <path d="M-14 26 h28 l-4 -26 h-20 Z" fill={PARCH_B} stroke={INK} strokeWidth="2.5" />
        <path d="M0 0 Q-16 -22 -6 -46" fill="none" stroke={NAVY} strokeWidth="3.5" strokeLinecap="round" />
        <path d="M0 0 Q10 -30 4 -54" fill="none" stroke={NAVY} strokeWidth="3.5" strokeLinecap="round" />
        <path d="M0 0 Q0 -18 0 -34" fill="none" stroke={NAVY} strokeWidth="3.5" strokeLinecap="round" />
      </g>

      {/* open notebook, center */}
      <g transform="translate(200 205)">
        <path d="M-110 0 L-6 -14 L-6 30 L-110 46 Z" fill={PARCH_A} stroke={INK} strokeWidth="3" />
        <path d="M110 0 L6 -14 L6 30 L110 46 Z" fill={PARCH_A} stroke={INK} strokeWidth="3" />
        <line x1="-6" y1="-14" x2="6" y2="-14" stroke={INK} strokeWidth="3" />
        {/* scribbled lines of notes */}
        <line x1="-92" y1="4" x2="-30" y2="-3" stroke={INK} strokeWidth="1.6" opacity="0.4" />
        <line x1="-92" y1="14" x2="-30" y2="7" stroke={INK} strokeWidth="1.6" opacity="0.4" />
        <line x1="-92" y1="24" x2="-40" y2="18" stroke={INK} strokeWidth="1.6" opacity="0.4" />
        <path d="M30 -3 q10 -6 20 0 t20 0" fill="none" stroke={GOLD} strokeWidth="2" opacity="0.85" />
        <line x1="24" y1="10" x2="86" y2="4" stroke={INK} strokeWidth="1.6" opacity="0.4" />
        <line x1="24" y1="20" x2="76" y2="15" stroke={INK} strokeWidth="1.6" opacity="0.4" />
      </g>

      {/* candle, right */}
      <g transform="translate(324 176)">
        <path d="M0 -18 Q6 -30 0 -40 Q-6 -30 0 -18 Z" fill={GOLD_LT} opacity="0.9" />
        <rect x="-10" y="-18" width="20" height="46" rx="4" fill={PARCH_B} stroke={INK} strokeWidth="2.5" />
      </g>

      {/* pencil */}
      <g transform="translate(150 236) rotate(-8)">
        <rect x="0" y="0" width="70" height="7" rx="2" fill={NAVY} />
        <path d="M70 0 l12 3.5 l-12 3.5 Z" fill={PARCH_A} stroke={INK} strokeWidth="1.5" />
      </g>
    </svg>
  )
}

type HorizonKind = 'today' | 'days' | 'week' | 'weeks'

/** Small per-pill doodle for the time-horizon step. One consistent line
 *  family; the metaphor shifts from urgent (ringing clock) to unhurried
 *  (growing sprout) as the horizon widens. */
export function HorizonIcon({ kind, className }: { kind: HorizonKind; className?: string }) {
  const common = { viewBox: '0 0 48 48', className, role: 'img' as const, 'aria-hidden': true }
  if (kind === 'today') {
    return (
      <svg {...common}>
        <circle cx="24" cy="26" r="16" fill={PARCH_A} stroke={INK} strokeWidth="2.5" />
        <path d="M24 26 L24 15 M24 26 L32 30" stroke={INK} strokeWidth="2.5" strokeLinecap="round" />
        <path d="M13 8 L18 13 M35 8 L30 13" stroke={GOLD} strokeWidth="2.5" strokeLinecap="round" />
        <path d="M6 22 q-3 4 0 8 M42 22 q3 4 0 8" stroke={NAVY} strokeWidth="2.2" strokeLinecap="round" fill="none" opacity="0.8" />
      </svg>
    )
  }
  if (kind === 'days') {
    return (
      <svg {...common}>
        <rect x="8" y="10" width="32" height="30" rx="4" fill={PARCH_A} stroke={INK} strokeWidth="2.5" />
        <line x1="8" y1="18" x2="40" y2="18" stroke={INK} strokeWidth="2" />
        <line x1="16" y1="6" x2="16" y2="14" stroke={NAVY} strokeWidth="2.5" strokeLinecap="round" />
        <line x1="32" y1="6" x2="32" y2="14" stroke={NAVY} strokeWidth="2.5" strokeLinecap="round" />
        <text x="24" y="33" textAnchor="middle" fontSize="14" fontWeight="700" fill={GOLD} fontFamily="var(--tok-font-mono)">3</text>
      </svg>
    )
  }
  if (kind === 'week') {
    return (
      <svg {...common}>
        <rect x="8" y="10" width="32" height="30" rx="4" fill={PARCH_A} stroke={INK} strokeWidth="2.5" />
        <line x1="8" y1="18" x2="40" y2="18" stroke={INK} strokeWidth="2" />
        <line x1="16" y1="6" x2="16" y2="14" stroke={NAVY} strokeWidth="2.5" strokeLinecap="round" />
        <line x1="32" y1="6" x2="32" y2="14" stroke={NAVY} strokeWidth="2.5" strokeLinecap="round" />
        {[0, 1, 2, 3, 4, 5, 6].map(i => (
          <rect key={i} x={11 + (i % 4) * 7} y={22 + Math.floor(i / 4) * 8} width="5" height="5" rx="1"
            fill={i < 5 ? GOLD : 'none'} stroke={INK} strokeWidth="1" opacity={i < 5 ? 0.85 : 0.35} />
        ))}
      </svg>
    )
  }
  // 2+ weeks — unhurried: a sprout taking its time
  return (
    <svg {...common}>
      <path d="M10 40 h28" stroke={INK} strokeWidth="2.5" strokeLinecap="round" />
      <path d="M24 40 V20" stroke={NAVY} strokeWidth="3" strokeLinecap="round" />
      <path d="M24 24 Q14 18 12 8" fill="none" stroke={NAVY} strokeWidth="3" strokeLinecap="round" />
      <path d="M24 30 Q34 24 36 14" fill="none" stroke={NAVY} strokeWidth="3" strokeLinecap="round" />
      <circle cx="12" cy="8" r="3.5" fill={GOLD_LT} stroke={INK} strokeWidth="1.5" />
      <circle cx="36" cy="14" r="3.5" fill={GOLD_LT} stroke={INK} strokeWidth="1.5" />
      <circle cx="24" cy="16" r="4" fill={GOLD} stroke={INK} strokeWidth="1.5" />
    </svg>
  )
}
