/**
 * build-microsims-manifest.ts — condenses mindcraft-content-engine's full
 * MicroSim extraction corpus (data/microsim_extracts/*.json, 4,013 files /
 * ~88MB as of 2026-08-23) into ONE small manifest the webhook can serve.
 *
 * Why a manifest and not the content: the corpus is far too large to check
 * into this repo or bundle into a serverless function (median extract is
 * ~19.5KB because each carries its sim's full file contents), and far too
 * large to bundle into the iOS app binary (only the 123-sim Calculus set is
 * bundled today, see MicroSimLoader.swift). But every extract records
 * exactly where its real files live upstream (source_url → Dan McCreary's
 * own GitHub repos), so the manifest stores per sim only the metadata the
 * Archive list needs (subject/title/description) plus the fetch coordinates
 * (repo/branch/path/entry/assets) that let microsims.ts assemble the full
 * sim on demand from raw.githubusercontent.com. Same "small derived
 * projection of a bigger real corpus, regenerated by script, not by hand"
 * shape as dans-books.json (see archive-books.ts's doc comment for the
 * bug-class precedent that established it).
 *
 * Filename-key subtlety (measured, not assumed): in each extract's `files`
 * dict the ENTRY file is normalized to the key "main.html" even when the
 * upstream file is named something else (62 of 4,013 — e.g. led.html);
 * `entry_file` preserves the real upstream name, so THAT is what goes in
 * the manifest's `entry` (verified live: raw…/led/led.html → 200,
 * raw…/led/main.html → 404). Asset keys (.js/.css) keep their upstream
 * relative paths verbatim (including "./x.js" and "../../css/y.css" forms),
 * which is exactly the text the entry HTML references them by — microsims.ts
 * relies on that for inlining.
 *
 * Rerunnable (repo convention: pipelines are scripts, not one-offs):
 *   npm run build-microsims-manifest --prefix webhook
 *   npm run build-microsims-manifest --prefix webhook -- /path/to/microsim_extracts
 */

import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

const SOURCE_DIR = process.argv[2]
  ? resolve(process.argv[2])
  : resolve(__dirname, '../../../mindcraft-content-engine/data/microsim_extracts')
const OUT_FILE = resolve(__dirname, '../data/microsims-manifest.json')
const DESCRIPTION_MAX = 160

type Extract = {
  source_repo?: string
  sim_dir?: string
  source_url?: string
  entry_file?: string
  title?: string | null
  description?: string | null
  dublin_core?: { description?: string | null } | null
  files?: Record<string, string> | null
  extraction_ok?: boolean
}

export type ManifestSim = {
  id: string
  repo: string
  branch: string
  /** Directory path within the repo, e.g. "docs/sims/unit-circle". */
  path: string
  /** Upstream entry filename — NOT the normalized local "main.html" key. */
  entry: string
  /** Relative .js/.css refs, verbatim as the entry HTML references them. */
  assets: string[]
  subject: string
  title: string
  description: string
}

function humanize(slug: string): string {
  return slug
    .split(/[-_]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

function clip(value: unknown, max: number): string {
  const text = String(value ?? '').replace(/\s+/g, ' ').trim()
  return text.length > max ? `${text.slice(0, max - 1)}…` : text
}

function main() {
  if (!existsSync(SOURCE_DIR)) {
    console.error(
      `No microsim_extracts directory at ${SOURCE_DIR} — run ` +
        `microsim_extractor.py in mindcraft-content-engine first, or pass the dir as an argument.`,
    )
    process.exit(1)
  }

  const files = readdirSync(SOURCE_DIR).filter((f) => f.endsWith('.json')).sort()
  const sims: ManifestSim[] = []
  let skipped = 0

  for (const file of files) {
    const raw = JSON.parse(readFileSync(resolve(SOURCE_DIR, file), 'utf8')) as Extract
    const repo = raw.source_repo ?? ''
    const dir = raw.sim_dir ?? ''
    const entry = raw.entry_file ?? ''
    const urlMatch = /^https:\/\/github\.com\/([^/]+\/[^/]+)\/tree\/([^/]+)\/(.+)$/.exec(
      raw.source_url ?? '',
    )
    if (!raw.extraction_ok || !repo || !dir || !entry || !urlMatch) {
      skipped += 1
      continue
    }
    const fileKeys = Object.keys(raw.files ?? {})
    sims.push({
      id: `${repo.replace(/\//g, '__')}__${dir}`,
      repo,
      branch: urlMatch[2],
      path: urlMatch[3].replace(/\/+$/, ''),
      entry,
      assets: fileKeys.filter((k) => k.endsWith('.js') || k.endsWith('.css')),
      subject: humanize(repo.split('/').pop() ?? repo),
      title: raw.title || humanize(dir),
      description: clip(raw.description ?? raw.dublin_core?.description ?? '', DESCRIPTION_MAX),
    })
  }

  sims.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))
  const manifest = { generatedAt: new Date().toISOString(), count: sims.length, sims }
  writeFileSync(OUT_FILE, JSON.stringify(manifest))
  console.log(
    `Wrote ${sims.length} sims (${skipped} skipped) from ${SOURCE_DIR} → ${OUT_FILE} ` +
      `(${(JSON.stringify(manifest).length / 1e6).toFixed(2)}MB)`,
  )
}

main()
