#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import { execFile } from 'node:child_process'
import http from 'node:http'
import { ROOT, dateArg, harvest, lintVocab, verifyAuthorship, schedule, writePost, writeJson, readJson } from './lib.mjs'
import { renderPosts, lintComposition, renderPdf } from './render.mjs'
import { buildReview, buildContactSheet } from './review.mjs'
import { publishRun } from './drive.mjs'
import { validateResearch, validateTestimonials, privacyGate } from './sources.mjs'
import { angleWrite, judgePersonality } from './llm.mjs'

const [command,...args]=process.argv.slice(2); const option=name=>{const i=args.indexOf(`--${name}`);return i>=0?args[i+1]:undefined}; const date=dateArg(option('date')); const runRel=`marketing/run/${date}`; const runDir=path.resolve(ROOT,runRel)

function personality(post){
 const lines=[post.hook,post.caption,...post.slides.flatMap(s=>Object.values(s.copy))].filter(x=>typeof x==='string'); const cite=lines[0]||''
 const traits={cinematic:{pass:/trap|path|motion|stakes|threshold|scene|story|route/i.test(lines.join(' ')),line:lines.find(x=>/trap|path|motion|stakes|threshold|scene|story|route/i.test(x))||cite},electric:{pass:/There it is|reveal|changes everything|becomes visible/i.test(lines.join(' ')),line:lines.find(x=>/There it is|reveal|changes everything|becomes visible/i.test(x))||cite},certain:{pass:!/[?]\s*$|might|maybe|possibly/i.test(post.caption),line:post.caption},human:{pass:/you|2am|gave up/i.test(lines.join(' ')),line:lines.find(x=>/you|2am|gave up/i.test(x))||cite},unflinching:{pass:/gap|trap|miss|stakes/i.test(lines.join(' ')),line:lines.find(x=>/gap|trap|miss|stakes/i.test(x))||cite}}; const score=Object.values(traits).filter(x=>x.pass).length
 return {score,traits,note:Object.entries(traits).map(([k,v])=>`${k} ${v.pass?'✓':'✗'} “${String(v.line).slice(0,90)}”`).join(' · '),judge:'deterministic fallback; replace with registered LLM judge when configured'}
}

async function doHarvest(){const candidates=harvest();writeJson(`${runRel}/candidates.json`,candidates);console.log(`Harvested ${candidates.length} candidates → ${runRel}/candidates.json`);return candidates}
async function doBuild(){fs.mkdirSync(runDir,{recursive:true});const sourceGate={research:validateResearch(),testimonials:validateTestimonials()};writeJson(`${runRel}/source-gates.json`,sourceGate);if(!sourceGate.research.valid||!sourceGate.testimonials.valid)throw new Error('Human-authored source validation failed; see source-gates.json');const candidates=harvest();for(const c of candidates)c.privacy=privacyGate(c);writeJson(`${runRel}/candidates.json`,candidates);const eligible=candidates.filter((c,i)=>c.privacy.status==='pass'&&lintVocab(writePost(c,date,i)).status!=='block');const batch=schedule(eligible);let posts=batch.candidates.map((c,i)=>writePost(c,date,i));if(args.includes('--llm')){for(let i=0;i<posts.length;i++){try{posts[i]=await angleWrite(batch.candidates[i],posts[i])}catch(error){posts[i].llm={writer:{status:'fallback',error:error.message}}}}}for(const p of posts){p.gate.vocab=lintVocab({caption:p.caption,slides:p.slides.map(s=>s.copy)});p.gate.authorship=verifyAuthorship(p);if(args.includes('--llm')){try{p.gate.personality=await judgePersonality(p)}catch(error){p.gate.personality={...personality(p),judge_error:error.message}}}else p.gate.personality=personality(p)}await renderPosts(posts,runDir);for(let i=0;i<posts.length;i++){const p=posts[i];p.gate.composition=lintComposition(p);p.gate.privacy=batch.candidates[i].privacy;const blocked=p.gate.vocab.status==='block'||p.gate.authorship.status==='block'||p.gate.privacy.status==='block';p.status=blocked?'blocked':p.gate.composition.status==='fail'||p.gate.personality.score<3?'needs_edit':'ready'}writeJson(`${runRel}/posts.json`,posts);writeJson(`${runRel}/batch.json`,{...batch,candidates:batch.candidates.map(x=>x.id),llm_requested:args.includes('--llm')});buildReview(date,posts);console.log(`Built ${posts.length} posts / ${batch.slidesUsed} slides → ${runRel}`)}
function loadPosts(){return readJson(`${runRel}/posts.json`)}
function doReview(){buildReview(date,loadPosts());const port=Number(option('port')||4174);const server=http.createServer((req,res)=>{if(req.method==='POST'&&req.url==='/api/decisions'){let body='';req.on('data',c=>body+=c);req.on('end',()=>{try{const value=JSON.parse(body);writeJson(`${runRel}/decisions.json`,value);res.writeHead(204).end()}catch{res.writeHead(400).end('Invalid JSON')}});return}const raw=req.url==='/'?`/marketing/review/${date}.html`:decodeURIComponent(req.url.split('?')[0]);const file=path.resolve(ROOT,'.'+raw);if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404).end('Not found');return}const ext=path.extname(file);res.setHeader('content-type',ext==='.html'?'text/html; charset=utf-8':ext==='.png'?'image/png':'application/octet-stream');fs.createReadStream(file).pipe(res)});server.listen(port,'127.0.0.1',()=>{const url=`http://127.0.0.1:${port}/`;console.log(`Review page: ${url}`);if(!args.includes('--no-open')){const opener=process.platform==='darwin'?'open':process.platform==='win32'?'cmd':'xdg-open';execFile(opener,process.platform==='win32'?['/c','start',url]:[url],()=>{})}})}
function doExport(){const posts=loadPosts(), decisions=readJson(`${runRel}/decisions.json`), map=decisions.decisions||decisions;let count=0;for(const p of posts){const d=map[p.id]?.decision||map[p.id];if(d!=='approved')continue;const out=path.join(runDir,'export',p.id.slice(-3));fs.mkdirSync(out,{recursive:true});for(const s of p.slides)fs.copyFileSync(path.join(runDir,p.id.slice(-3),`slide-${s.n}.png`),path.join(out,`slide-${s.n}.png`));fs.writeFileSync(path.join(out,'caption.txt'),p.caption+'\n');fs.writeFileSync(path.join(out,'alt.txt'),p.slides.map(s=>`Slide ${s.n}: ${s.alt}`).join('\n')+'\n');fs.writeFileSync(path.join(out,'hashtags.txt'),p.hashtags.slice(0,8).join(' ')+'\n');count++}console.log(`Exported ${count} approved posts → ${runRel}/export`)}

async function doContactSheet(){const posts=loadPosts();const html=buildContactSheet(date,posts);const pdf=path.join(runDir,`marketing-batch-${date}.pdf`);await renderPdf(html,pdf);console.log(`Contact sheet → ${path.relative(ROOT,pdf)}`);return pdf}
async function doPublish(){const posts=loadPosts();const pdf=await doContactSheet();const result=await publishRun(date,runDir,posts,{contactSheetPdf:pdf});writeJson(`${runRel}/drive.json`,result);console.log(`Published ${result.posts_published} posts (${result.files.length} files) → ${result.root_folder_url}`);console.log(`Filed by post type: ${[...new Set(posts.filter(p=>p.status!=='blocked').map(p=>p.pillar))].join(', ')}`);if(result.posts_withheld_blocked)console.log(`Withheld ${result.posts_withheld_blocked} blocked post(s); blocked content never leaves the repo.`)}

try{if(command==='harvest')await doHarvest();else if(command==='build')await doBuild();else if(command==='review')doReview();else if(command==='export')doExport();else if(command==='contact-sheet')await doContactSheet();else if(command==='publish')await doPublish();else throw new Error('Usage: cli.mjs harvest|build|review|export|contact-sheet|publish [--date YYYY-MM-DD]')}catch(error){console.error(error.message);process.exitCode=1}
