import fs from 'node:fs'
import path from 'node:path'
import { ROOT, escapeHtml } from './lib.mjs'

export function buildReview(date, posts) {
 const relative=`../run/${date}`
 const cards=posts.map((p,i)=>`<article data-id="${p.id}" tabindex="0"><header><b>POST ${p.id.slice(-3)} · ${escapeHtml(p.pillar.replaceAll('_',' '))} · ${p.audience} · ${p.slides.length} slides · ${p.status.toUpperCase()}</b></header><div class="slides">${p.slides.map(s=>`<img src="${relative}/${p.id.slice(-3)}/slide-${s.n}.png" alt="${escapeHtml(s.alt)}">`).join('')}</div><textarea readonly>${escapeHtml(p.caption)}</textarea><button data-copy>Copy caption</button><section><h3>Why this</h3><p>${escapeHtml(p.evidence.stat)}</p><h3>Brand gate ${p.gate.vocab.status.toUpperCase()}</h3><p>Vocabulary ${p.gate.vocab.status} · authorship ${p.gate.authorship.status} · privacy ${p.gate.privacy?.status||'pass'} · image ${p.gate.composition.status}</p><h3>Personality ${p.gate.personality.score} of 5</h3><p>${escapeHtml(p.gate.personality.note)}</p></section><div><button data-decision="approved">Approve</button><button data-decision="rejected">Reject</button><button data-decision="needs_edit">Edit</button></div></article>`).join('')
 const html=`<!doctype html><html><head><meta charset="utf-8"><title>Marketing review ${date}</title><style>:root{color-scheme:dark}body{margin:0;padding:40px;background:#080e14;color:#f5f5f5;font:16px Arial}nav{position:sticky;top:0;background:#080e14;padding:16px;z-index:2}article{max-width:1100px;margin:30px auto;padding:24px;border:1px solid #1d3a8a}article.active{outline:3px solid #c4f547}.slides{display:flex;gap:12px;overflow:auto;margin:20px 0}.slides img{width:260px;height:325px;object-fit:cover}textarea{width:100%;height:90px;background:#101d29;color:#f5f5f5}button{margin:8px;padding:10px 16px}article[data-state="approved"]{border-color:#c4f547}article[data-state="rejected"]{opacity:.5}</style></head><body><nav><button id="export">Export decisions</button> J/K navigate · A approve · X reject · E edit</nav>${cards}<script>
const key='mindcraft-marketing-${date}', cards=[...document.querySelectorAll('article')]; let state=JSON.parse(localStorage.getItem(key)||'{}'), at=0;
function paint(){cards.forEach((c,i)=>{c.classList.toggle('active',i===at);c.dataset.state=state[c.dataset.id]||''})} function decide(v){state[cards[at].dataset.id]={decision:v,decided_at:new Date().toISOString()};localStorage.setItem(key,JSON.stringify(state));paint()}
document.addEventListener('click',e=>{const c=e.target.closest('article');if(c)at=cards.indexOf(c);if(e.target.dataset.decision)decide(e.target.dataset.decision);if(e.target.dataset.copy)navigator.clipboard.writeText(c.querySelector('textarea').value);paint()});document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='j')at=Math.min(cards.length-1,at+1);if(e.key.toLowerCase()==='k')at=Math.max(0,at-1);if(e.key.toLowerCase()==='a')decide('approved');if(e.key.toLowerCase()==='x')decide('rejected');if(e.key.toLowerCase()==='e')decide('needs_edit');paint()});
document.querySelector('#export').onclick=async()=>{const response=await fetch('/api/decisions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({date:'${date}',decisions:state})});if(!response.ok)return alert('Decision export failed');alert('Decisions written to marketing/run/${date}/decisions.json')};paint();</script></body></html>`
 const out=path.resolve(ROOT,`marketing/review/${date}.html`);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,html);return out
}

// Print-oriented twin of the review page. Drive cannot run the interactive page, so the
// batch travels as a PDF that previews and takes inline comments natively.
export function buildContactSheet(date, posts) {
 const relative=`../run/${date}`
 const cards=posts.map(p=>`<article><h2>Post ${p.id.slice(-3)} · ${escapeHtml(p.pillar.replaceAll('_',' '))} · ${p.audience} · ${p.status.toUpperCase()}</h2><div class="slides">${p.slides.map(s=>`<figure><img src="${relative}/${p.id.slice(-3)}/slide-${s.n}.png" alt="${escapeHtml(s.alt)}"><figcaption>Slide ${s.n} · ${escapeHtml(s.alt)}</figcaption></figure>`).join('')}</div><h3>Caption</h3><pre>${escapeHtml(p.caption)}</pre><p class="tags">${escapeHtml(p.hashtags.slice(0,8).join(' '))}</p><h3>Why this</h3><p>${escapeHtml(p.evidence.stat)}</p><p class="src">${escapeHtml(p.evidence.source_file)} · ${escapeHtml(p.evidence.source_id)}</p><h3>Gates</h3><p>Vocabulary ${p.gate.vocab.status} · authorship ${p.gate.authorship.status} · privacy ${p.gate.privacy?.status||'pass'} · image ${p.gate.composition.status}</p><h3>Personality ${p.gate.personality.score} of 5</h3><p>${escapeHtml(p.gate.personality.note)}</p></article>`).join('')
 const html=`<!doctype html><html><head><meta charset="utf-8"><title>MindCraft marketing batch ${date}</title><style>@page{size:A4;margin:16mm}body{margin:0;background:#fff;color:#111;font:12px Arial}h1{font-size:22px;margin:0 0 4px}article{page-break-inside:avoid;break-inside:avoid;border-top:2px solid #1d3a8a;padding:14px 0;margin:0}h2{font-size:15px;margin:0 0 8px}h3{font-size:11px;text-transform:uppercase;letter-spacing:.1em;color:#555;margin:12px 0 4px}.slides{display:flex;gap:10px;flex-wrap:wrap}figure{margin:0;width:150px}figure img{width:150px;height:187px;object-fit:cover;border:1px solid #ccc}figcaption{font-size:9px;color:#555;margin-top:4px}pre{white-space:pre-wrap;font:12px Arial;background:#f4f4f4;padding:10px;margin:0}.tags{color:#1d3a8a}.src{color:#777;font-size:10px}</style></head><body><h1>MindCraft marketing batch ${date}</h1><p>${posts.length} posts · ${posts.reduce((n,p)=>n+p.slides.length,0)} slides · comment inline to approve or reject</p>${cards}</body></html>`
 const out=path.resolve(ROOT,`marketing/review/${date}-contact-sheet.html`);fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,html);return out
}
